- alias: Hallway lights idle
  trigger:
    - platform: state
      entity_id: input_boolean.lights_needed
      to: 'on'
    - platform: state
      entity_id: input_boolean.lights_needed
      to: 'off'
    - platform: state
      entity_id: input_boolean.hallway_occupied
      to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.hallway_motion_detection_enabled
      state: 'on'
  action:
    - service: script.turn_on
      data_template:
        entity_id: >-
          {% if is_state('input_boolean.lights_needed', 'on') %}
          script.scene_hallway_dim
          {% else %}
          script.scene_hallway_off
          {% endif %}

- alias: Hallway lights occupied
  trigger:
    - platform: state
      entity_id: input_boolean.hallway_occupied
      to: 'on'
  action:
    - service: script.turn_on
      data_template:
        entity_id: >-
          {% if is_state('input_boolean.everyone_asleep', 'on') %}
          script.scene_hallway_night
          {% elif is_state('input_boolean.lights_full', 'on') %}
          script.scene_hallway_full
          {% else %}
          script.scene_hallway_normal
          {% endif %}
