- alias: Disable hallway motion on button click
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: hallway_dimmer
        event: 4003
  condition:
    - condition: state
      entity_id: input_boolean.hallway_motion_detection_enabled
      state: 'on'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.hallway_motion_detection_enabled

- alias: Enable hallway motion
  trigger:
    - platform: state
      entity_id: binary_sensor.hallway_motion
      to: 'off'
      for: '01:00:00'
    - platform: event
      event_type: deconz_event
      event_data:
        id: hallway_dimmer
        event: 1003
  condition:
    - condition: state
      entity_id: input_boolean.hallway_motion_detection_enabled
      state: 'off'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.hallway_motion_detection_enabled
    - service: scene.turn_on
      data_template:
        entity_id: >-
          {% if is_state('input_boolean.light_mode', 'on') %}
          scene.hallway_dim
          {% else %}
          scene.hallway_off
          {% endif %}
