- id: '1606748199081'
  alias: Tag White card 1 is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: C3-4D-74-40
  condition: []
  action:
  - type: toggle
    device_id: 8b622aadc79b455cb42dcc931faf8af1
    entity_id: light.bedroom_window_lamp
    domain: light
  mode: single
