homeassistant:
  latitude: !secret latitude
  longitude: !secret longitude
  packages: !include_dir_named package
  auth_providers:
    - type: homeassistant
  allowlist_external_dirs:
    - /tmp
  external_url: !secret homeassistant_external_url

api:
cloud:
config:
conversation:
history:
logbook:
map:
mobile_app:
person:
sun:
system_health:
default_config:

logger:
  default: info
  logs:
    homeassistant.components.zha: debug
    zigpy: debug

recorder:
  db_url: !secret recorder_db_url

ifttt:
  key: !secret ifttt_key

# For loading HACS themes
frontend:
  themes: !include_dir_merge_named themes

# For frontend automation support
automation: !include automations.yaml
