homeassistant:
  name: !secret homeassistant_name
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 20
  unit_system: metric
  time_zone: Europe/Stockholm
  packages: !include_dir_named package
  customize: !include customize.yaml
  customize_domain:
    automation:
      initial_state: 'on'
  customize_glob:
    "script.scene_*":
      can_cancel: false
      icon: mdi:circle-expand
  auth_providers:
    - type: homeassistant

frontend:
  themes: !include_dir_merge_named themes

api:
cloud:
config:
conversation:
history:
logbook:
map:
mobile_app:
person:
sun:
system_health:
updater:

recorder:
  db_url: !secret recorder_db_url
  purge_interval: 2
  purge_keep_days: 2

ifttt:
  key: !secret ifttt_key

asuswrt:
  host: !secret asuswrt_host
  protocol: telnet
  port: 23
  username: !secret asuswrt_username
  password: !secret asuswrt_password

emulated_hue:
  expose_by_default: true
  exposed_domains:
    - light

deconz:
  host: !secret deconz_host
  api_key: !secret deconz_api_key
  port: !secret deconz_port

hacs:
  token: !secret hacs_token

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret xiaomi_gateway_key

automation: !include automations.yaml
