homeassistant:
  name: !secret homeassistant_name
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 17
  unit_system: metric
  time_zone: Europe/Stockholm
  packages: !include_dir_named package
  customize: !include customize.yaml
  customize_domain:
    automation:
      initial_state: 'on'
  auth_providers:
    - type: homeassistant
  allowlist_external_dirs:
    - /tmp

api:
cloud:
config:
conversation:
history:
logbook:
map:
mobile_app:
person:
sun:
system_health:
updater:
default_config:

recorder:
  db_url: !secret recorder_db_url

ifttt:
  key: !secret ifttt_key

# For loading HACS themes
frontend:
  themes: !include_dir_merge_named themes

# For frontend automation support
automation: !include automations.yaml
