homeassistant:
  name: !secret homeassistant_name
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 20
  unit_system: metric
  time_zone: Europe/Stockholm
  packages: !include_dir_named package
  customize: !include customize.yaml
  customize_domain:
    automation:
      initial_state: 'on'
  customize_glob:
    "script.scene_*":
      can_cancel: false
      icon: mdi:circle-expand
  auth_providers:
    - type: homeassistant

frontend:
  themes: !include_dir_merge_named themes

api:
cloud:
config:
conversation:
history:
logbook:
map:
mobile_app:
person:
sun:
system_health:
updater:

recorder:
  db_url: !secret recorder_db_url
  purge_interval: 2
  purge_keep_days: 2

apcupsd:
  host: !secret apcupsd_host

ifttt:
  key: !secret ifttt_key

asuswrt:
  host: !secret asuswrt_host
  protocol: telnet
  port: 23
  username: !secret asuswrt_username
  password: !secret asuswrt_password

remote:
  - platform: harmony
    name: Living Room
    host: !secret harmony_host

emulated_hue:
  expose_by_default: true
  exposed_domains:
    - light

deconz:
  host: !secret deconz_host
  api_key: !secret deconz_api_key
  port: !secret deconz_port

hacs:
  token: !secret hacs_token

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret xiaomi_gateway_key

vacuum:
  - platform: xiaomi_miio
    host: !secret vacuum_xiaomi_host
    token: !secret vacuum_xiaomi_token
    name: !secret vacuum_xiaomi_name

alarm_control_panel:
  - platform: manual
    name: 'Alarm'
    code: !secret alarm_code
    pending_time: 60
    trigger_time: 120
    disarm_after_trigger: false
    armed_home:
      pending_time: 0
    armed_night:
      pending_time: 0
    armed_away:
      pending_time: 30
    triggered:
      pending_time: 60

input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
sensor: !include_dir_merge_list sensor
switch: !include_dir_merge_list switch
binary_sensor: !include_dir_merge_list binary_sensor
group: !include_dir_merge_named group
scene: !include_dir_merge_list scene
script: !include_dir_merge_named script
notify: !include_dir_merge_list notify
automation: !include automations.yaml
automation old: !include_dir_merge_list automation
