homeassistant:
  name: !secret homeassistant_name
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 20
  unit_system: metric
  time_zone: Europe/Stockholm
  packages: !include_dir_named package
  customize: !include customize.yaml
  customize_domain:
    automation:
      initial_state: 'on'
  auth_providers:
    - type: homeassistant
    - type: legacy_api_password
      api_password: !secret http_password

#introduction:
# discovery:
# updater:

frontend:
  themes: !include themes.yaml

config:

conversation:

history:

logbook:

sun:

ios:

api:

system_health:

mobile_app:

http:
  server_port: !secret http_server_port
  ip_ban_enabled: true
  login_attempts_threshold: 5
  use_x_forwarded_for: True
  base_url: !secret http_base_url
  ssl_certificate: !secret http_ssl_certificate
  ssl_key: !secret http_ssl_key
  trusted_proxies:
    - !secret trusted_proxies_001
    - !secret trusted_proxies_002
    - !secret trusted_proxies_003
    - !secret trusted_proxies_004
    - !secret trusted_proxies_005
    - !secret trusted_proxies_006
    - !secret trusted_proxies_007
    - !secret trusted_proxies_008
    - !secret trusted_proxies_009
    - !secret trusted_proxies_010
    - !secret trusted_proxies_011
    - !secret trusted_proxies_012
    - !secret trusted_proxies_013
    - !secret trusted_proxies_014
    - !secret trusted_proxies_015

alexa:
  smart_home:
    filter:
      include_domains:
        - light
        - sensor
        - switch
        - scene
        - binary_sensor
        - vacuum
        - input_boolean

recorder:
  db_url: !secret recorder_db_url
  purge_interval: 2
  purge_keep_days: 2

apcupsd:
  host: !secret apcupsd_host

ifttt:
  key: !secret ifttt_key

asuswrt:
  host: !secret asuswrt_host
  protocol: telnet
  port: 23
  username: !secret asuswrt_username
  password: !secret asuswrt_password

# media_player:
#   - platform: spotify
#     client_id: !secret spotify_client_id
#     client_secret: !secret spotify_client_secret
#   - platform: samsungtv
#     host: !secret samsungtv_host
#     mac: !secret samsungtv_mac
#     scan_interval: 20
  # - platform: plex
  #   include_non_clients: true
  #   scan_interval: 10
  #   use_episode_art: true

remote:
  - platform: harmony
    name: Living Room
    host: !secret harmony_host

# Disabled
# zwave:
#   usb_path: /dev/ttyACM0
#   network_key: !secret zwave_network_key

emulated_hue:
  expose_by_default: true
  exposed_domains:
    - light

switch:
  - platform: flux
    lights:
      - light.bedroom_ceiling_lamp
      - light.bedroom_lamp
      - light.living_room_window_lamp
      - light.bathroom_ceiling_lamp_left
      - light.bathroom_ceiling_lamp_middle
      - light.bathroom_ceiling_lamp_right
      - light.kitchen_window_lamp
      - light.kitchen_ceiling_lamp
      - light.guest_bedroom_ceiling_lamp
      - light.guest_bedroom_window_lamp
    name: Flux Indoor Lights
    stop_time: '22:00'
    start_colortemp: 4000
    sunset_colortemp: 3000
    stop_colortemp: 1900
    disable_brightness_adjust: True
    mode: mired
    transition: 2
  - platform: flux
    lights:
      - light.kitchen_countertop_lightstrip
    name: Flux Kitchen
    stop_time: '22:00'
    start_colortemp: 4000
    sunset_colortemp: 3000
    stop_colortemp: 1900
    disable_brightness_adjust: True
    mode: mired
    transition: 2
  - platform: flux
    lights:
      - light.hallway_ceiling_lamp
    name: Flux Hallway
    stop_time: '22:00'
    start_colortemp: 4000
    sunset_colortemp: 3000
    stop_colortemp: 1900
    disable_brightness_adjust: True
    mode: mired
    transition: 2
  - platform: flux
    lights:
      - light.living_room_ceiling_lamp
      - light.living_room_globe
    name: Flux Living Room
    stop_time: '22:00'
    start_colortemp: 4000
    sunset_colortemp: 3000
    stop_colortemp: 1900
    disable_brightness_adjust: True
    mode: mired
    transition: 2

yeelight:
  devices:
    10.0.0.122:
      name: Living Room TV Light
      transition: 1000
      use_music_mode: False
      save_on_change: False
    10.0.0.102:
      name: Johnnys Bedlight
      use_music_mode: False
      save_on_change: False
    10.0.0.186:
      name: Kajsas Bedlight
      use_music_mode: False
      save_on_change: False

# influxdb:
#   host: !secret influxdb_host

aarlo:
  username: !secret arlo_username
  password: !secret arlo_password
  mode_api: v1

deconz:
  host: !secret deconz_host
  api_key: !secret deconz_api_key
  port: !secret deconz_port

hacs:
  token: !secret hacs_token

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret xiaomi_gateway_key

vacuum:
  - platform: xiaomi_miio
    host: !secret vacuum_xiaomi_host
    token: !secret vacuum_xiaomi_token
    name: !secret vacuum_xiaomi_name

homekit:
  auto_start: True
  filter:
    include_domains:
      - light
    include_entities:
      - input_boolean.johnny_asleep
      - input_boolean.kajsa_asleep
      - input_boolean.guest_asleep
      - input_boolean.everyone_asleep
      - alarm_control_panel.alarm
      - switch.balcony_switch
      - switch.guest_bedroom_switch
      - switch.hallway_switch
      - switch.kitchen_switch

camera:
  - platform: aarlo
    ffmpeg_arguments: '-pred 1 -q:v 2'

alarm_control_panel:
  - platform: manual
    name: 'Alarm'
    code: !secret alarm_code
    pending_time: 60
    trigger_time: 120
    disarm_after_trigger: false
    armed_home:
      pending_time: 0
    armed_night:
      pending_time: 0
    armed_away:
      pending_time: 30
    triggered:
      pending_time: 60
  - platform: aarlo
    home_mode_name: armed
    away_mode_name: vacation

input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
sensor: !include_dir_merge_list sensor
binary_sensor: !include_dir_merge_list binary_sensor
group: !include_dir_merge_named group
scene: !include_dir_merge_list scene
automation: !include_dir_merge_list automation
notify: !include_dir_merge_list notify
script: !include scripts.yaml
