# :root = http://[host]/api/[key]

# Get all
GET :root/sensors

###########

# Update
PUT :root/sensors/7
Content-Type: application/json
{
  "name": "Bedroom Environment Temperature"
}

# Get
GET :root/sensors/8

# Update
PUT :root/sensors/8
Content-Type: application/json
{
  "name": "Bedroom Environment Humidity"
}

# Get
GET :root/sensors/9

# Update
PUT :root/sensors/9
Content-Type: application/json
{
  "name": "Bedroom Environment Switch"
}

# Get
GET :root/sensors/10

# Update
PUT :root/sensors/10
Content-Type: application/json
{
  "name": "Bedroom Environment Switch 2"
}

###########

# Get
GET :root/sensors/15

# Update name
PUT :root/sensors/15
Content-Type: application/json
{
  "name": "Bathroom Environment Temperature"
}

# Get
GET :root/sensors/16

# Update
PUT :root/sensors/16
Content-Type: application/json
{
  "name": "Bathroom Environment Humidity"
}

# Get
GET :root/sensors/17

# Update
PUT :root/sensors/17
Content-Type: application/json
{
  "name": "Bathroom Environment Switch"
}