# :root = http://[host]/api/[key]

# Get all
GET :root/sensors

###########

# Update
PUT :root/sensors/7
Content-Type: application/json
{
  "name": "Bedroom Environment Temperature"
}

# Get
GET :root/sensors/8

# Update
PUT :root/sensors/8
Content-Type: application/json
{
  "name": "Bedroom Environment Humidity"
}

# Get
GET :root/sensors/9

# Update
PUT :root/sensors/9
Content-Type: application/json
{
  "name": "Bedroom Environment Switch"
}

# Get
GET :root/sensors/10

# Update
PUT :root/sensors/10
Content-Type: application/json
{
  "name": "Bedroom Environment Switch 2"
}

###########

# Get
GET :root/sensors/12

# Update name
PUT :root/sensors/12
Content-Type: application/json
{
  "name": "Bathroom Environment Temperature"
}

# Get
GET :root/sensors/13

# Update
PUT :root/sensors/13
Content-Type: application/json
{
  "name": "Bathroom Environment Humidity"
}

# Get
GET :root/sensors/20

# Update
PUT :root/sensors/20
Content-Type: application/json
{
  "name": "Bathroom Environment Switch"
}

# Get
GET :root/sensors/21

# Update
PUT :root/sensors/21
Content-Type: application/json
{
  "name": "Bathroom Environment Switch 2"
}

# Get
GET :root/sensors/20
