- alias: Bathroom lights idle
  trigger:
    - platform: state
      entity_id: input_boolean.lights_needed
      to: 'on'
    - platform: state
      entity_id: input_boolean.lights_needed
      to: 'off'
    - platform: state
      entity_id: input_boolean.bathroom_occupied
      to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.bathroom_motion_detection_enabled
      state: 'on'
  action:
    - service: scene.turn_on
      data_template:
        entity_id: >-
          {% if is_state('input_boolean.lights_needed', 'on') %}
          scene.bathroom_dim
          {% else %}
          scene.bathroom_off
          {% endif %}

- alias: Bathroom lights occupied
  trigger:
    - platform: state
      entity_id: input_boolean.bathroom_occupied
      to: 'on'
  action:
    - service: scene.turn_on
      data_template:
        entity_id: >-
          {% if is_state('input_boolean.everyone_asleep', 'on') %}
          scene.bathroom_night
          {% elif is_state('input_boolean.lights_full', 'on') %}
          scene.bathroom_full
          {% else %}
          scene.bathroom_normal
          {% endif %}

