- alias: Bathroom lights dim or off
  trigger:
    - platform: state
      entity_id: input_boolean.lights_needed
      to: 'on'
    - platform: state
      entity_id: input_boolean.lights_needed
      to: 'off'
    - platform: state
      entity_id: binary_sensor.bathroom_motion
      to: 'off'
      for: '00:04:00'
    - platform: numeric_state
      entity_id: sensor.bathroom_humidity
      below: 60
  condition:
    - condition: state
      entity_id: input_boolean.bathroom_motion_detection_enabled
      state: 'on'
    - condition: numeric_state
      entity_id: sensor.bathroom_humidity
      below: 60
    - condition: state
      entity_id: binary_sensor.bathroom_motion
      state: 'off'
      for: '00:04:00'
  action:
    - service: scene.turn_on
      data_template:
        entity_id: >-
          {% if is_state('input_boolean.lights_needed', 'on') %}
          scene.bathroom_dim
          {% else %}
          scene.bathroom_off
          {% endif %}

- alias: Bathroom lights normal or night
  trigger:
    - platform: state
      entity_id: binary_sensor.bathroom_motion
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.bathroom_motion_detection_enabled
      state: 'on'
    - condition: state
      entity_id: light.bathroom_ceiling_lamp
      state: 'off'
  action:
    - service: scene.turn_on
      data_template:
        entity_id: >-
          {% if is_state('input_boolean.everyone_asleep', 'on') %}
          scene.bathroom_night
          {% elif is_state('input_boolean.lights_full', 'on') %}
          scene.bathroom_full
          {% else %}
          scene.bathroom_normal
          {% endif %}
