- alias: Bathroom lights idle
  trigger:
    - platform: state
      entity_id: input_boolean.lights_needed
      to: 'on'
    - platform: state
      entity_id: input_boolean.lights_needed
      to: 'off'
    - platform: state
      entity_id: input_boolean.bathroom_occupied
      to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.bathroom_motion_detection_enabled
      state: 'on'
  action:
    - service: script.turn_on
      data_template:
        entity_id: script.scene_bathroom_{{ state_attr('sensor.light_mode', 'off_mode') }}

- alias: Bathroom lights occupied
  trigger:
    - platform: state
      entity_id: input_boolean.bathroom_occupied
      to: 'on'
  action:
    - service: script.turn_on
      data_template:
        entity_id: script.scene_bathroom_{{ states('sensor.light_mode') }}
