- alias: Toggle Johnny Asleep
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: johnny_asleep
        event: 1000
  condition:
    - condition: state
      entity_id: device_tracker.johnnysiphone
      state: 'home'
  action:
    - service: input_boolean.toggle
      entity_id: input_boolean.johnny_asleep

- alias: Toggle Kajsa Asleep
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: kajsa_asleep
        event: 1000
  condition:
    - condition: state
      entity_id: device_tracker.kajsasiphone
      state: 'home'
  action:
    - service: input_boolean.toggle
      entity_id: input_boolean.kajsa_asleep

- alias: Toggle Lea Asleep
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: lea_asleep
        event: 1000
  action:
    - service: input_boolean.toggle
      entity_id: input_boolean.lea_asleep
