- alias: Bedroom lights idle
  trigger:
    - platform: state
      entity_id: input_boolean.lights_needed
      to: 'on'
    - platform: state
      entity_id: input_boolean.lights_needed
      to: 'off'
    - platform: state
      entity_id: input_boolean.bedroom_occupied
      to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.bedroom_motion_detection_enabled
      state: 'on'
    - condition: state
      entity_id: light.johnnys_bedlight
      state: 'off'
    - condition: state
      entity_id: light.kajsas_bedlight
      state: 'off'
  action:
    - service: script.turn_on
      data_template:
        entity_id: >-
          {% if is_state('input_boolean.johnny_asleep', 'on') %}
          script.scene_bedroom_off
          {% elif is_state('input_boolean.kajsa_asleep', 'on') %}
          script.scene_bedroom_off
          {% elif is_state('input_boolean.lights_needed', 'on') %}
          script.scene_bedroom_dim
          {% else %}
          script.scene_bedroom_off
          {% endif %}

- alias: Bedroom lights occupied
  trigger:
    - platform: state
      entity_id: input_boolean.bedroom_occupied
      to: 'on'
    - platform: state
      entity_id: input_boolean.johnny_asleep
      to: 'off'
    - platform: state
      entity_id: input_boolean.kajsa_asleep
      to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.bedroom_motion_detection_enabled
      state: 'on'
    - condition: state
      entity_id: input_boolean.johnny_asleep
      state: 'off'
    - condition: state
      entity_id: input_boolean.kajsa_asleep
      state: 'off'
    - condition: state
      entity_id: light.johnnys_bedlight
      state: 'off'
    - condition: state
      entity_id: light.kajsas_bedlight
      state: 'off'
  action:
    - service: script.turn_on
      data_template:
        entity_id: >-
          {% if is_state('input_boolean.everyone_asleep', 'on') %}
          script.scene_bedroom_night
          {% elif is_state('input_boolean.lights_full', 'on') %}
          script.scene_bedroom_full
          {% else %}
          script.scene_bedroom_normal
          {% endif %}

- alias: Bedside light off on sleep and wakeup Johnny
  trigger:
    - platform: state
      entity_id: input_boolean.johnny_asleep
      to: 'on'
    - platform: state
      entity_id: input_boolean.johnny_asleep
      to: 'off'
  condition:
    - condition: state
      entity_id: light.johnnys_bedlight
      state: 'on'
  action:
    - service: light.turn_off
      data:
        entity_id: light.johnnys_bedlight

- alias: Bedside light off on sleep and wakeup Kajsa
  trigger:
    - platform: state
      entity_id: input_boolean.kajsa_asleep
      to: 'on'
    - platform: state
      entity_id: input_boolean.kajsa_asleep
      to: 'off'
  condition:
    - condition: state
      entity_id: light.kajsas_bedlight
      state: 'on'
  action:
    - service: light.turn_off
      data:
        entity_id: light.kajsas_bedlight

- alias: Bedside light on when Johnny is home
  trigger:
    - platform: time
      at: '21:02:00'
    - platform: state
      entity_id: device_tracker.johnnysiphone
      to: 'home'
  condition:
    - condition: time
      after: '21:00:00'
    - condition: state
      entity_id: device_tracker.johnnysiphone
      state: 'home'
    - condition: state
      entity_id: light.johnnys_bedlight
      state: 'off'
    - condition: state
      entity_id: input_boolean.johnny_asleep
      state: 'off'
    - condition: state
      entity_id: input_boolean.kajsa_asleep
      state: 'off'
  action:
    - service: light.turn_on
      data:
        entity_id: light.johnnys_bedlight
    - service: script.turn_on
      entity_id: script.scene_bedroom_off

- alias: Bedside light on when Kajsa is home
  trigger:
    - platform: time
      at: '21:02:00'
    - platform: state
      entity_id: device_tracker.kajsasiphone
      to: 'home'
  condition:
    - condition: time
      after: '21:00:00'
    - condition: state
      entity_id: device_tracker.kajsasiphone
      state: 'home'
    - condition: state
      entity_id: light.kajsas_bedlight
      state: 'off'
    - condition: state
      entity_id: input_boolean.kajsa_asleep
      state: 'off'
    - condition: state
      entity_id: input_boolean.johnny_asleep
      state: 'off'
  action:
    - service: light.turn_on
      data:
        entity_id: light.kajsas_bedlight
    - service: script.turn_on
      entity_id: script.scene_bedroom_off

- alias: Bedroom wakeup light Johnny
  trigger:
    - platform: time
      at: '06:55:00'
  condition:
    - condition: state
      entity_id: input_boolean.bedroom_wakeup_light
      state: 'on'
    - condition: state
      entity_id: binary_sensor.workday
      state: 'on'
    - condition: state
      entity_id: input_boolean.johnny_asleep
      state: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.johnnys_bedlight
        brightness_pct: 100
        transition: 180
        rgb_color: [255,160,39]

- alias: Bedroom wakeup light Kajsa
  trigger:
    - platform: time
      at: '06:55:00'
  condition:
    - condition: state
      entity_id: input_boolean.bedroom_wakeup_light
      state: 'on'
    - condition: state
      entity_id: binary_sensor.workday
      state: 'on'
    - condition: state
      entity_id: input_boolean.kajsa_asleep
      state: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.kajsas_bedlight
        brightness_pct: 100
        transition: 180
        rgb_color: [255,160,39]
