- alias: Bedroom lights idle
  trigger:
    - platform: state
      entity_id: input_boolean.lights_needed
      to: 'on'
    - platform: state
      entity_id: input_boolean.lights_needed
      to: 'off'
    - platform: state
      entity_id: input_boolean.bedroom_occupied
      to: 'off'
    - platform: state
      entity_id: input_boolean.johnny_asleep
      to: 'on'
    - platform: state
      entity_id: input_boolean.kajsa_asleep
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.bedroom_motion_detection_enabled
      state: 'on'
    - condition: state
      entity_id: light.johnnys_bedlight
      state: 'off'
    - condition: state
      entity_id: light.kajsas_bedlight
      state: 'off'
  action:
    - service: script.turn_on
      data_template:
        entity_id: >-
          {% if is_state('input_boolean.johnny_asleep', 'on') %}
          script.scene_bedroom_off
          {% elif is_state('input_boolean.kajsa_asleep', 'on') %}
          script.scene_bedroom_off
          {% else %}
          script.scene_bedroom_{{ state_attr('sensor.light_mode', 'off_mode') }}
          {% endif %}

- alias: Bedroom lights occupied
  trigger:
    - platform: state
      entity_id: input_boolean.bedroom_occupied
      to: 'on'
    - platform: state
      entity_id: input_boolean.johnny_asleep
      to: 'off'
    - platform: state
      entity_id: input_boolean.kajsa_asleep
      to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.bedroom_motion_detection_enabled
      state: 'on'
    - condition: state
      entity_id: input_boolean.johnny_asleep
      state: 'off'
    - condition: state
      entity_id: input_boolean.kajsa_asleep
      state: 'off'
    - condition: state
      entity_id: light.johnnys_bedlight
      state: 'off'
    - condition: state
      entity_id: light.kajsas_bedlight
      state: 'off'
  action:
    - service: script.turn_on
      data_template:
        entity_id: script.scene_bedroom_{{ states('sensor.light_mode') }}
