- alias: Bedroom lights on
  trigger:
    - platform: state
      entity_id: input_boolean.lights_needed
      to: 'on'
    - platform: state
      entity_id: binary_sensor.bedroom_motion_sensor
      to: 'off'
      for:
        minutes: 10
  condition:
    - condition: state
      entity_id: input_boolean.lights_needed
      state: 'on'
    - condition: state
      entity_id: input_boolean.bedroom_motion_detection_enabled
      state: 'on'
    - condition: state
      entity_id: group.sleep_status
      state: 'off'
    - condition: state
      entity_id: light.johnnys_bedlight
      state: 'off'
    - condition: state
      entity_id: light.kajsas_bedlight
      state: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.bedroom_cozy

- alias: Bedroom lights off
  trigger:
    platform: state
    entity_id: input_boolean.lights_needed
    to: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.bedroom_off

- alias: Bedroom lights normal when occupied
  trigger:
    - platform: state
      entity_id: binary_sensor.bedroom_motion_sensor
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.lights_needed
      state: 'on'
    - condition: state
      entity_id: input_boolean.bedroom_motion_detection_enabled
      state: 'on'
    - condition: state
      entity_id: group.sleep_status
      state: 'off'
    - condition: state
      entity_id: light.johnnys_bedlight
      state: 'off'
    - condition: state
      entity_id: light.kajsas_bedlight
      state: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.bedroom_normal

- alias: Bedroom lights off when one person goes to bed
  trigger:
    - platform: state
      entity_id: group.sleep_status
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.lights_needed
      state: 'on'
    - condition: state
      entity_id: input_boolean.everyone_asleep
      state: 'off'
  action:
    - delay: '00:01:00'
    - service: scene.turn_on
      entity_id: scene.bedroom_off

- alias: Bedside light on when Johnny is home
  trigger:
    - platform: time
      at: '21:00:00'
    - platform: state
      entity_id: device_tracker.johnnysiphone
      to: 'home'
  condition:
    - condition: time
      after: '21:00:00'
    - condition: state
      entity_id: device_tracker.johnnysiphone
      state: 'home'
    - condition: state
      entity_id: light.johnnys_bedlight
      state: 'off'
    - condition: state
      entity_id: input_boolean.johnny_asleep
      state: 'off'
  action:
    - service: light.turn_on
      data:
        entity_id: light.johnnys_bedlight
        brightness_pct: 1
        rgb_color: [255,128,0]
    - service: scene.turn_on
      entity_id: scene.bedroom_off

- alias: Bedside light off when Johnny goes to bed
  trigger:
    - platform: state
      entity_id: input_boolean.johnny_asleep
      to: 'on'
  condition:
    - condition: state
      entity_id: light.johnnys_bedlight
      state: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.johnnys_bedlight
        brightness_pct: 1
        rgb_color: [255,0,0]
    - delay: '00:01:00'
    - service: light.turn_off
      data:
        entity_id: light.johnnys_bedlight

- alias: Bedside light on when Kajsa is home
  trigger:
    - platform: time
      at: '21:00:00'
    - platform: state
      entity_id: device_tracker.kajsasiphone
      to: 'home'
  condition:
    - condition: time
      after: '21:00:00'
    - condition: state
      entity_id: device_tracker.kajsasiphone
      state: 'home'
    - condition: state
      entity_id: light.kajsas_bedlight
      state: 'off'
    - condition: state
      entity_id: input_boolean.kajsa_asleep
      state: 'off'
  action:
    - service: light.turn_on
      data:
        entity_id: light.kajsas_bedlight
        brightness_pct: 1
        rgb_color: [255,128,0]
    - service: scene.turn_on
      entity_id: scene.bedroom_off

- alias: Bedside light off when Kajsa goes to bed
  trigger:
    - platform: state
      entity_id: input_boolean.kajsa_asleep
      to: 'on'
  condition:
    - condition: state
      entity_id: light.kajsas_bedlight
      state: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.kajsas_bedlight
        brightness_pct: 1
        rgb_color: [255,0,0]
    - delay: '00:01:00'
    - service: light.turn_off
      data:
        entity_id: light.kajsas_bedlight
