- alias: Bedroom lights on
  trigger:
    - platform: state
      entity_id: input_boolean.lights_needed
      to: 'on'
    - platform: state
      entity_id: binary_sensor.bedroom_motion
      to: 'off'
      for: '00:10:00'
  condition:
    - condition: state
      entity_id: input_boolean.lights_needed
      state: 'on'
    - condition: state
      entity_id: input_boolean.bedroom_motion_detection_enabled
      state: 'on'
    - condition: state
      entity_id: input_boolean.johnny_asleep
      state: 'off'
    - condition: state
      entity_id: input_boolean.kajsa_asleep
      state: 'off'
    - condition: state
      entity_id: input_boolean.lea_asleep
      state: 'off'
    - condition: state
      entity_id: light.johnnys_bedlight
      state: 'off'
    - condition: state
      entity_id: light.kajsas_bedlight
      state: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.bedroom_dim

- alias: Bedroom lights off
  trigger:
    platform: state
    entity_id: input_boolean.lights_needed
    to: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.bedroom_off

- alias: Bedroom lights normal when occupied
  trigger:
    - platform: state
      entity_id: binary_sensor.bedroom_motion
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.lights_needed
      state: 'on'
    - condition: state
      entity_id: input_boolean.bedroom_motion_detection_enabled
      state: 'on'
    - condition: state
      entity_id: input_boolean.johnny_asleep
      state: 'off'
    - condition: state
      entity_id: input_boolean.kajsa_asleep
      state: 'off'
    - condition: state
      entity_id: input_boolean.lea_asleep
      state: 'off'
    - condition: state
      entity_id: light.johnnys_bedlight
      state: 'off'
    - condition: state
      entity_id: light.kajsas_bedlight
      state: 'off'
    - condition: state
      entity_id: light.bedroom_ceiling_lamp
      state: 'off'
  action:
    - service: scene.turn_on
      data_template:
        entity_id: >-
          {% if is_state('input_boolean.lights_full', 'on') %}
          scene.bedroom_full
          {% elif is_state('input_boolean.lights_needed', 'on') %}
          scene.bedroom_normal
          {% endif %}

- alias: Bedroom lights off when one person goes to bed
  trigger:
    - platform: state
      entity_id: input_boolean.johnny_asleep
      to: 'on'
    - platform: state
      entity_id: input_boolean.kajsa_asleep
      to: 'on'
    - platform: state
      entity_id: input_boolean.lea_asleep
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.lights_needed
      state: 'on'
    - condition: state
      entity_id: input_boolean.everyone_asleep
      state: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.bedroom_off

- alias: Bedside light on when Johnny is home
  trigger:
    - platform: time
      at: '21:00:00'
    - platform: state
      entity_id: device_tracker.johnnysiphone
      to: 'home'
  condition:
    - condition: time
      after: '21:00:00'
    - condition: state
      entity_id: device_tracker.johnnysiphone
      state: 'home'
    - condition: state
      entity_id: light.johnnys_bedlight
      state: 'off'
    - condition: state
      entity_id: input_boolean.johnny_asleep
      state: 'off'
    - condition: state
      entity_id: input_boolean.kajsa_asleep
      state: 'off'
    - condition: state
      entity_id: input_boolean.lea_asleep
      state: 'off'
  action:
    - service: light.turn_on
      data:
        entity_id: light.johnnys_bedlight
    - service: scene.turn_on
      entity_id: scene.bedroom_off

- alias: Bedside light off when Johnny goes to bed
  trigger:
    - platform: state
      entity_id: input_boolean.johnny_asleep
      to: 'on'
  condition:
    - condition: state
      entity_id: light.johnnys_bedlight
      state: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.johnnys_bedlight
        rgb_color: [255,0,0]
    - delay: '00:01:00'
    - service: light.turn_off
      data:
        entity_id: light.johnnys_bedlight

- alias: Bedside light on when Kajsa is home
  trigger:
    - platform: time
      at: '21:00:00'
    - platform: state
      entity_id: device_tracker.kajsasiphone
      to: 'home'
  condition:
    - condition: time
      after: '21:00:00'
    - condition: state
      entity_id: device_tracker.kajsasiphone
      state: 'home'
    - condition: state
      entity_id: light.kajsas_bedlight
      state: 'off'
    - condition: state
      entity_id: input_boolean.kajsa_asleep
      state: 'off'
    - condition: state
      entity_id: input_boolean.johnny_asleep
      state: 'off'
    - condition: state
      entity_id: input_boolean.lea_asleep
      state: 'off'
  action:
    - service: light.turn_on
      data:
        entity_id: light.kajsas_bedlight
    - service: scene.turn_on
      entity_id: scene.bedroom_off

- alias: Bedside light off when Kajsa goes to bed
  trigger:
    - platform: state
      entity_id: input_boolean.kajsa_asleep
      to: 'on'
  condition:
    - condition: state
      entity_id: light.kajsas_bedlight
      state: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.kajsas_bedlight
        rgb_color: [255,0,0]
    - delay: '00:01:00'
    - service: light.turn_off
      data:
        entity_id: light.kajsas_bedlight
