- alias: Living room lights dim or off
  trigger:
    - platform: state
      entity_id: input_boolean.lights_needed
      to: 'on'
    - platform: state
      entity_id: input_boolean.lights_needed
      to: 'off'
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.living_room_lights
  condition:
    - condition: state
      entity_id: input_boolean.living_room_motion_detection_enabled
      state: 'on'
    - condition: state
      entity_id: timer.living_room_lights
      state: 'idle'
    - condition: state
      entity_id: input_select.harmony
      state: 'PowerOff'
  action:
    - service: scene.turn_on
      data_template:
        entity_id: >-
          {% if is_state('input_boolean.lights_needed', 'on') %}
          scene.living_room_dim
          {% else %}
          scene.living_room_off
          {% endif %}

- alias: Living room motion detected
  trigger:
    - platform: state
      entity_id: binary_sensor.living_room_motion_sensor
      to: 'on'
    - platform: state
      entity_id: input_select.harmony
      to: 'PowerOff'
  condition:
    - condition: state
      entity_id: input_boolean.living_room_motion_detection_enabled
      state: 'on'
    - condition: state
      entity_id: input_select.harmony
      state: 'PowerOff'
  action:
    - service: timer.cancel
      entity_id: timer.living_room_lights
    - service: scene.turn_on
      data_template:
        entity_id: >-
          {% if is_state('input_boolean.everyone_asleep', 'on') %}
          scene.living_room_night
          {% elif is_state('input_boolean.lights_full', 'on') %}
          scene.living_room_full
          {% else %}
          scene.living_room_normal
          {% endif %}
    - service: switch.flux_living_room_update

- alias: Living room motion idle
  trigger:
    - platform: state
      entity_id: binary_sensor.living_room_motion
      to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.living_room_motion_detection_enabled
      state: 'on'
  action:
    - service: timer.start
      data:
        entity_id: timer.living_room_lights
        duration: '00:05:00'

- alias: Living room TV on
  trigger:
    - platform: state
      entity_id: input_select.harmony
      to: 'TV'
    - platform: state
      entity_id: input_select.harmony
      to: 'Movies'
    - platform: state
      entity_id: input_select.harmony
      to: 'Music'
    - platform: state
      entity_id: input_boolean.lights_needed
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.living_room_motion_detection_enabled
      state: 'on'
    - condition: state
      entity_id: input_boolean.everyone_asleep
      state: 'off'
  action:
    - service: scene.turn_on
      data_template:
        entity_id: >-
          {% if (is_state('input_select.harmony', 'TV') or is_state('input_select.harmony', 'Movies')) and is_state('input_boolean.lights_needed', 'on') %}
          scene.living_room_tv
          {% elif (is_state('input_select.harmony', 'TV') or is_state('input_select.harmony', 'Movies')) and is_state('input_boolean.lights_needed', 'off') %}
          scene.living_room_tv_only
          {% elif is_state('input_select.harmony', 'Music') and is_state('input_boolean.lights_needed', 'on') %}
          scene.living_room_music
          {% elif is_state('input_select.harmony', 'Music') and is_state('input_boolean.lights_needed', 'off') %}
          scene.living_room_music_only
          {% elif is_state('input_select.harmony', 'PowerOff') and is_state('input_boolean.lights_needed', 'on') %}
          scene.living_room_dim
          {% else %}
          scene.living_room_off
          {% endif %}
