- alias: Living room lights on
  trigger:
    - platform: state
      entity_id: input_boolean.lights_needed
      to: 'on'
    - platform: state
      entity_id: binary_sensor.living_room_motion_sensor
      to: 'off'
      for: '00:10:00'
  condition:
    - condition: state
      entity_id: input_boolean.lights_needed
      state: 'on'
    - condition: state
      entity_id: input_boolean.living_room_motion_detection_enabled
      state: 'on'
    - condition: state
      entity_id: binary_sensor.living_room_motion_sensor
      state: 'off'
      for: '00:10:00'
  action:
    - service: scene.turn_on
      data_template:
        entity_id: >-
          {% if is_state('input_boolean.lights_full', 'on') %}
          scene.living_room_full
          {% elif is_state('input_select.harmony', 'PowerOff') %}
          scene.living_room_dim
          {% elif is_state('input_select.harmony', 'Movies') %}
          scene.living_room_tv
          {% elif is_state('input_select.harmony', 'TV') %}
          scene.living_room_tv
          {% elif is_state('input_select.harmony', 'Music') %}
          scene.living_room_music
          {% endif %}

- alias: Living room lights off
  trigger:
    - platform: state
      entity_id: input_boolean.lights_needed
      to: 'off'
  condition:
    - condition: state
      entity_id: binary_sensor.living_room_motion_sensor
      state: 'off'
      for: '00:10:00'
  action:
    - service: scene.turn_on
      entity_id: scene.living_room_off

- alias: Living room lights normal when occupied
  trigger:
    - platform: state
      entity_id: binary_sensor.living_room_motion_sensor
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.lights_needed
      state: 'on'
    - condition: state
      entity_id: input_boolean.living_room_motion_detection_enabled
      state: 'on'
    - condition: state
      entity_id: input_select.harmony
      state: 'PowerOff'
  action:
    - service: scene.turn_on
      entity_id: scene.living_room_normal
    - service: switch.flux_living_room_update

- alias: Living room lights on when motion during night
  trigger:
    - platform: state
      entity_id: binary_sensor.living_room_motion_sensor
      to: 'on'
  condition:
    - condition: state
      entity_id: input_select.harmony
      state: 'PowerOff'
    - condition: state
      entity_id: input_boolean.everyone_asleep
      state: 'on'
    - condition: state
      entity_id: input_boolean.living_room_motion_detection_enabled
      state: 'on'
    - condition: state
      entity_id: input_boolean.lights_night
      state: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.living_room_night

- alias: Living room lights off when no motion during the night
  trigger:
    - platform: state
      entity_id: binary_sensor.living_room_motion_sensor
      to: 'off'
      for: '00:01:00'
  condition:
    - condition: state
      entity_id: input_select.harmony
      state: 'PowerOff'
    - condition: state
      entity_id: input_boolean.everyone_asleep
      state: 'on'
    - condition: state
      entity_id: input_boolean.living_room_motion_detection_enabled
      state: 'on'
    - condition: state
      entity_id: input_boolean.lights_night
      state: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.living_room_off
