- alias: Disable living room motion on button click
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: living_room_dimmer
        event: 4003
  condition:
    - condition: state
      entity_id: input_boolean.living_room_motion_detection_enabled
      state: 'on'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.living_room_motion_detection_enabled

- alias: Enable living room motion
  trigger:
    - platform: state
      entity_id: binary_sensor.living_room_motion_sensor
      to: 'off'
      for: '01:00:00'
    - platform: event
      event_type: deconz_event
      event_data:
        id: living_room_dimmer
        event: 1003
  condition:
    - condition: state
      entity_id: input_boolean.living_room_motion_detection_enabled
      state: 'off'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.living_room_motion_detection_enabled
    - service: script.turn_on
      data_template:
        entity_id: script.scene_living_room_{{ states('sensor.light_mode') }}
