- alias: Living room lights in TV mode when tv on and lights needed
  trigger:
    - platform: state
      entity_id: input_select.harmony
      to: 'TV'
    - platform: state
      entity_id: input_select.harmony
      to: 'Movies'
  condition:
    - condition: state
      entity_id: input_boolean.lights_needed
      state: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.living_room_tv

- alias: Living room lights in TV mode when tv on and lights not needed
  trigger:
    - platform: state
      entity_id: input_select.harmony
      to: 'TV'
    - platform: state
      entity_id: input_select.harmony
      to: 'Movies'
  condition:
    - condition: state
      entity_id: input_boolean.lights_needed
      state: 'off'
    - condition: state
      entity_id: input_boolean.everyone_asleep
      state: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.living_room_tv_only

- alias: Living room lights in music mode when music on and lights needed
  trigger:
    - platform: state
      entity_id: input_select.harmony
      to: 'Music'
  condition:
    - condition: state
      entity_id: input_boolean.lights_needed
      state: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.living_room_music
    - service: switch.flux_living_room_update

- alias: Living room lights in music mode when music on and lights not needed
  trigger:
    - platform: state
      entity_id: input_select.harmony
      to: 'Music'
  condition:
    - condition: state
      entity_id: input_boolean.lights_needed
      state: 'off'
    - condition: state
      entity_id: input_boolean.everyone_asleep
      state: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.living_room_music_only

- alias: Living room lights in normal mode when tv off and lights needed
  trigger:
    - platform: state
      entity_id: input_select.harmony
      to: 'PowerOff'
  condition:
    - condition: state
      entity_id: input_boolean.lights_needed
      state: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.living_room_normal
    - service: switch.flux_living_room_update

- alias: Living room lights in normal mode when tv off
  trigger:
    - platform: state
      entity_id: input_select.harmony
      to: 'PowerOff'
  condition:
    - condition: state
      entity_id: input_boolean.lights_needed
      state: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.living_room_off
