automation:
  - alias: Trigger alarm when perimiter breached when armed_night
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.main_entrance
          - binary_sensor.balcony_entrance
          - binary_sensor.living_room_window_right
          - binary_sensor.living_room_window_left
          - binary_sensor.bathroom_window
          - binary_sensor.kitchen_window_left
          - binary_sensor.kitchen_window_right
          - binary_sensor.guest_bedroom_window
        to: 'on'
    condition:
      - condition: state
        entity_id: alarm_control_panel.alarm
        state: 'armed_night'
    action:
      - service: alarm_control_panel.alarm_trigger
        entity_id: alarm_control_panel.alarm

  - alias: Trigger alarm when perimiter breached when armed_away
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.main_entrance
          - binary_sensor.balcony_entrance
          - binary_sensor.bedroom_window
          - binary_sensor.living_room_window_left
          - binary_sensor.living_room_window_right
          - binary_sensor.bathroom_window
          - binary_sensor.kitchen_window_left
          - binary_sensor.kitchen_window_right
          - binary_sensor.guest_bedroom_window
        to: 'on'
      - platform: state
        entity_id: alarm_control_panel.aarlo_home
        to: 'triggered'
    condition:
      - condition: state
        entity_id: alarm_control_panel.alarm
        state: 'armed_away'
    action:
      - service: alarm_control_panel.alarm_trigger
        entity_id: alarm_control_panel.alarm

  - alias: Trigger alarm when motion detected when armed_away and vacation
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.bedroom_motion
          - binary_sensor.living_room_motion_sensor
          - binary_sensor.hallway_motion
          - binary_sensor.bathroom_motion
          - binary_sensor.kitchen_motion
          - binary_sensor.guest_bedroom_motion
        to: 'on'
      - platform: state
        entity_id: alarm_control_panel.aarlo_home
        to: 'triggered'
    condition:
      - condition: state
        entity_id: alarm_control_panel.alarm
        state: 'armed_away'
      - condition: state
        entity_id: input_binary.vacation_mode
        state: 'on'
      - condition: state
        entity_id: input_binary.guest_mode
        state: 'off'
    action:
      - service: alarm_control_panel.alarm_trigger
        entity_id: alarm_control_panel.alarm
