automation:
  - alias: Automatically arm alarm when away
    id: bbda9bf1-762e-4c91-896e-e89243b96769
    trigger:
      - platform: state
        entity_id: person.johnny
        from: 'home'
        to: 'not_home'
      - platform: state
        entity_id: person.kajsa
        from: 'home'
        to: 'not_home'
    condition:
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
    - condition: state
      entity_id: input_boolean.alarm_mode
      state: 'on'
    - condition: state
      entity_id: group.household
      state: 'not_home'
    action:
      - service: alarm_control_panel.alarm_arm_away
        entity_id: alarm_control_panel.alarm
        data:
          code: !secret alarm_code

  - alias: Automatically disarm alarm when home
    id: 25bcdb92-7a84-4fc8-b636-674696384c1d
    trigger:
      - platform: state
        entity_id: person.johnny
        from: 'not_home'
        to: 'home'
      - platform: state
        entity_id: person.kajsa
        from: 'not_home'
        to: 'home'
    condition:
    - condition: state
      entity_id: input_boolean.alarm_mode
      state: 'on'
    action:
      - service: alarm_control_panel.alarm_disarm
        entity_id: alarm_control_panel.alarm
        data:
          code: !secret alarm_code
