automation:
  - alias: Alarm armed away
    id: feb2e477-d1ce-4731-af54-970cf4cdab04
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm
        to: 'armed_away'
    action:
      - service: alarm_control_panel.alarm_arm_home
        entity_id: alarm_control_panel.aarlo_home
      - service: input_boolean.turn_off
        entity_id:
          - input_boolean.johnny_asleep
          - input_boolean.kajsa_asleep
          - input_boolean.lea_asleep

  - alias: Alarm disarmed
    id: a437755a-1718-4610-9d64-1ee60b0319db
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm
        to: 'disarmed'
    action:
      - service: aarlo.siren_off
        entity_id: switch.aarlo_siren_home
      - service: alarm_control_panel.alarm_disarm
        entity_id: alarm_control_panel.aarlo_home

  - alias: Alarm triggered while armed_night
    id: 74ff92b7-4523-407d-bdad-3e5556c6608a
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm
        from: 'armed_night'
        to: 'triggered'
    action:
      - service: script.turn_on
        entity_id: script.scene_home_full
      - service: aarlo.camera_start_recording
        data:
          entity_id:
            - camera.aarlo_hallway
            - camera.aarlo_living_room
          duration: 60
      - service: tts.google_translate_say
        data:
          entity_id: media_player.bedroom_tts
          message: >-
            Alarm triggered!
            {%- for state in states.binary_sensor -%}
              {% set type = state.name.split(' ') | last -%}
              {% if type == 'Window' and state.state_with_unit == 'on' %}
                {{- state.name }} is open.
              {%- endif -%}
              {% if type == 'Door' and state.state_with_unit == 'on' %}
                {{- state.name }} is open.
              {%- endif -%}
            {%- endfor %}

  - alias: Alarm triggered while armed_home
    id: b27c94e0-9a82-4ff7-9a2d-a0c3372b1a29
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm
        from: 'armed_home'
        to: 'triggered'
    action:
      - service: script.turn_on
        entity_id: script.scene_home_full
      - service: aarlo.camera_start_recording
        data:
          entity_id:
            - camera.aarlo_hallway
            - camera.aarlo_living_room
          duration: 60
      - service: tts.google_translate_say
        data:
          entity_id:
            - media_player.bathroom_tts
            - media_player.bedroom_tts
            - media_player.office_tts
            - media_player.living_room_tts
          message: >-
            Alarm triggered!
            {%- for state in states.binary_sensor -%}
              {% set type = state.name.split(' ') | last -%}
              {% if type == 'Window' and state.state_with_unit == 'on' %}
                {{- state.name }} is open.
              {%- endif -%}
              {% if type == 'Door' and state.state_with_unit == 'on' %}
                {{- state.name }} is open.
              {%- endif -%}
            {%- endfor %}

  - alias: Alarm triggered
    id: 5b8c70a0-fe14-4f7f-9ae7-70372eede85a
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm
        from: 'pending'
        to: 'triggered'
    action:
      - service: script.turn_on
        entity_id: script.scene_home_full
      - service: aarlo.camera_start_recording
        data:
          entity_id:
            - camera.aarlo_hallway
            - camera.aarlo_living_room
          duration: 60
      - service: aarlo.siren_on
        data:
          entity_id: switch.aarlo_siren_home
          volume: 8
          duration: 30

  - alias: Alarm pending
    id: 96bfc88d-e039-4716-926b-e6b9df9a5957
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm
        from: 'armed_away'
        to: 'pending'
    action:
      - service: aarlo.siren_on
        data:
          entity_id: switch.aarlo_siren_home
          volume: 1
          duration: 10
