automation:
  # TBD: Is this needed?
  # - alias: Alarm notify armed away
  #   trigger:
  #     - platform: state
  #       entity_id: alarm_control_panel.alarm
  #       to: 'armed_away'
  #   action:
  #     - service: notify.all_phones
  #       data:
  #         title: "Alarm has been armed"
  #         message: "The alarm has been set to armed_away"

  - alias: Alarm notify disarmed
    id: 7909f6c0-738b-4627-b4ce-36abe280a572
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm
        to: 'disarmed'
    condition:
      - condition: state
        entity_id: group.household
        state: 'not_home'
    action:
      - service: notify.all_phones
        data:
          title: "Alarm has been disarmed"
          message: "No household member is currently home."

  - alias: Alarm notify triggered
    id: b8c09f57-fdfd-46cd-bbf4-24359a8d62d5
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm
        to: 'triggered'
    action:
      - service: notify.all_phones
        data:
          title: '** Home Alarm Triggered **'
          message: 'Check camera recording immediately'
