automation:
  - alias: Alarm armed away
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm
        to: 'armed_away'
    action:
      - service: notify.all_phones
        data:
          title: "Alarm has been armed"
          message: "The alarm has been set to armed_away"
      - service: alarm_control_panel.alarm_arm_home
        entity_id: alarm_control_panel.aarlo_home
      - service: light.turn_on
        data:
          entity_id: light.gateway_light_7811dc64de1a
          brightness_pct: 100
          rgb_color: [255,0,0]
      - delay: '00:00:10'
      - service: light.turn_off
        data:
          entity_id: light.gateway_light_7811dc64de1a
      - service: input_boolean.turn_off
        entity_id:
          - input_boolean.johnny_asleep
          - input_boolean.kajsa_asleep
          - input_boolean.guest_asleep

  - alias: Alarm disarmed
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm
        to: 'disarmed'
    action:
      - service: notify.all_phones
        data:
          title: "Alarm has been disarmed"
          message: "The alarm has been set to disarmed"
      - service: alarm_control_panel.alarm_disarm
        entity_id: alarm_control_panel.aarlo_home
      - service: light.turn_on
        data:
          entity_id: light.gateway_light_7811dc64de1a
          brightness_pct: 100
          rgb_color: [0,255,0]
      - delay: '00:00:10'
      - service: light.turn_off
        data:
          entity_id: light.gateway_light_7811dc64de1a

  - alias: Alarm triggered
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm
        to: 'triggered'
    action:
      - service: script.turn_on
        entity_id: script.scene_home_full
      - service: camera.aarlo_start_recording
        data:
          entity_id: camera.aarlo_hallway
          duration: 60
      - service: camera.aarlo_start_recording
        data:
          entity_id: camera.aarlo_living_room
          duration: 60
      - service: notify.all_phones
        data:
          title: '** Home Alarm Triggered **'
          message: 'Check camera recording immediately'
      - service: light.turn_on
        data:
          entity_id: light.gateway_light_7811dc64de1a
          brightness_pct: 100
          rgb_color: [255,0,0]
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret xiaomi_gateway_mac
          ringtone_id: 3
          ringtone_vol: 10

  - alias: Alarm pending
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm
        from: 'armed_away'
        to: 'pending'
    action:
      - service: light.turn_on
        data:
          entity_id: light.gateway_light_7811dc64de1a
          brightness_pct: 100
          rgb_color: [255,255,0]
      - service: xiaomi_aqara.play_ringtone
        data:
          gw_mac: !secret xiaomi_gateway_mac
          ringtone_id: 26
          ringtone_vol: 5
