automation:
  - alias: Alarm armed away
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm
        to: 'armed_away'
    action:
      - service: alarm_control_panel.alarm_arm_home
        entity_id: alarm_control_panel.aarlo_home
      - service: input_boolean.turn_off
        entity_id:
          - input_boolean.johnny_asleep
          - input_boolean.kajsa_asleep
          - input_boolean.guest_asleep

  - alias: Alarm disarmed
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm
        to: 'disarmed'
    action:
      - service: switch.turn_off
        entity_id: switch.aarlo_home_siren
      - service: alarm_control_panel.alarm_disarm
        entity_id: alarm_control_panel.aarlo_home

  - alias: Alarm triggered
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm
        to: 'triggered'
    action:
      - service: script.turn_on
        entity_id: script.scene_home_full
      - service: camera.aarlo_start_recording
        data:
          entity_id: camera.aarlo_hallway
          duration: 60
      - service: camera.aarlo_start_recording
        data:
          entity_id: camera.aarlo_living_room
          duration: 60
      - service: switch.turn_on
        entity_id: switch.aarlo_home_siren

  - alias: Alarm pending
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm
        from: 'armed_away'
        to: 'pending'
    action:
      - service: switch.turn_on
        entity_id: switch.aarlo_home_siren
