automation:
  - alias: Automatically arm alarm when away
    trigger:
      - platform: state
        entity_id: group.household
        from: 'home'
        to: 'not_home'
    condition:
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
    - condition: state
      entity_id: input_boolean.alarm_mode
      state: 'on'
    action:
      - service: alarm_control_panel.alarm_arm_away
        entity_id: alarm_control_panel.alarm
        data:
          code: !secret alarm_code

  - alias: Automatically disarm alarm when home
    trigger:
      - platform: state
        entity_id: group.household
        from: 'not_home'
        to: 'home'
    condition:
    - condition: state
      entity_id: input_boolean.alarm_mode
      state: 'on'
    action:
      - service: alarm_control_panel.alarm_disarm
        entity_id: alarm_control_panel.alarm
        data:
          code: !secret alarm_code
