- alias: Kitchen lights idle
  trigger:
    - platform: state
      entity_id: sensor.light_mode
      to: 'off'
    - platform: state
      entity_id: sensor.light_mode
      to: 'normal'
    - platform: state
      entity_id: sensor.light_mode
      to: 'night'
    - platform: state
      entity_id: input_boolean.kitchen_occupied
      to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.kitchen_motion_detection_enabled
      state: 'on'
  action:
    - service: script.turn_on
      data_template:
        entity_id: script.scene_kitchen_{{ state_attr('sensor.light_mode', 'off_mode') }}

- alias: Kitchen lights occupied
  trigger:
    - platform: state
      entity_id: input_boolean.kitchen_occupied
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.kitchen_motion_detection_enabled
      state: 'on'
  action:
    - service: script.turn_on
      data_template:
        entity_id: script.scene_kitchen_{{ states('sensor.light_mode') }}
