- alias: Kitchen lights dim
  trigger:
    - platform: state
      entity_id: input_boolean.lights_needed
      to: 'on'
    - platform: state
      entity_id: binary_sensor.kitchen_motion
      to: 'off'
      for: '00:03:00'
  condition:
    - condition: state
      entity_id: input_boolean.lights_needed
      state: 'on'
    - condition: state
      entity_id: input_boolean.everyone_asleep
      state: 'off'
    - condition: state
      entity_id: input_boolean.kitchen_motion_detection_enabled
      state: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.kitchen_dim

- alias: Kitchen lights off
  trigger:
    - platform: state
      entity_id: input_boolean.lights_needed
      to: 'off'
    - platform: state
      entity_id: binary_sensor.kitchen_motion
      to: 'off'
      for: '00:03:00'
  condition:
    - condition: state
      entity_id: input_boolean.kitchen_motion_detection_enabled
      state: 'on'
    - condition: state
      entity_id: input_boolean.lights_needed
      state: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.kitchen_off

- alias: Kitchen lights normal when motion
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_motion
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.everyone_asleep
      state: 'off'
    - condition: state
      entity_id: input_boolean.kitchen_motion_detection_enabled
      state: 'on'
  action:
    - service: scene.turn_on
      data_template:
        entity_id: >-
          {% if is_state('input_boolean.lights_full', 'on') %}
          scene.kitchen_full
          {% elif is_state('input_boolean.lights_needed', 'on') %}
          scene.kitchen_normal
          {% elif is_state('input_boolean.lights_needed', 'off') %}
          scene.kitchen_countertop_only
          {% endif %}
    - delay: '00:00:03'
    - service: switch.flux_indoor_lights_update

- alias: Kitchen lights on dim on motion during the night
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_motion
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.everyone_asleep
      state: 'on'
    - condition: state
      entity_id: input_boolean.kitchen_motion_detection_enabled
      state: 'on'
    - condition: state
      entity_id: input_boolean.lights_night
      state: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.kitchen_night

- alias: Kitchen lights off when no motion during the night
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_motion
      to: 'off'
      for: '00:01:00'
  condition:
    - condition: state
      entity_id: input_boolean.everyone_asleep
      state: 'on'
    - condition: state
      entity_id: input_boolean.kitchen_motion_detection_enabled
      state: 'on'
    - condition: state
      entity_id: input_boolean.lights_night
      state: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.kitchen_off
