- alias: Kitchen occupied
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_motion
      to: 'on'
  action:
    - service: timer.cancel
      entity_id: timer.kitchen_lights
    - service: input_boolean.turn_on
      entity_id: input_boolean.kitchen_occupied

- alias: Kitchen start idle timer
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_motion
      to: 'off'
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: timer.kitchen_lights
          state: 'idle'
        - condition: state
          entity_id: timer.kitchen_lights
          state: 'active'
  action:
    - service: timer.start
      data:
        entity_id: timer.kitchen_lights
        duration: '00:10:00'

- alias: Kitchen idle
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.kitchen_lights
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.kitchen_occupied
