- alias: Disable kitchen motion on button click
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: kitchen_dimmer
        event: 4003
  condition:
    - condition: state
      entity_id: input_boolean.kitchen_motion_detection_enabled
      state: 'on'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.kitchen_motion_detection_enabled

- alias: Enable kitchen motion
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_motion
      to: 'off'
      for: '01:00:00'
    - platform: event
      event_type: deconz_event
      event_data:
        id: kitchen_dimmer
        event: 1003
  condition:
    - condition: state
      entity_id: input_boolean.kitchen_motion_detection_enabled
      state: 'off'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.kitchen_motion_detection_enabled
    - service: script.turn_on
      data_template:
        entity_id: script.scene_kitchen_{{ states('sensor.light_mode') }}

- alias: Kitchen send vacuum to trash
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: empty_vacuum
        event: 1002
  action:
    - service: script.turn_on
      entity_id: script.vacuum_go_trash

- alias: Kitchen send vacuum home
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: empty_vacuum
        event: 1003
  action:
    - service: script.turn_on
      entity_id: script.vacuum_go_home
