automation:
  - alias: Living room lights idle
    id: dd0680dd-fe71-443c-ae24-de514b59f8c6
    trigger:
      - platform: state
        entity_id: binary_sensor.living_room_occupied
        to: 'off'
      - platform: state
        entity_id: sensor.light_mode
    condition:
      - condition: state
        entity_id: binary_sensor.living_room_occupied
        state: 'off'
      - condition: state
        entity_id: binary_sensor.living_room_occupancy_automation
        state: 'on'
    action:
      - service: script.turn_on
        data_template:
          entity_id: script.scene_living_room_{{ state_attr('sensor.light_mode', 'off_mode') }}

  - alias: Living room lights occupied
    id: 03406399-9a26-4729-87d2-7e0ca59eccac
    trigger:
      - platform: state
        entity_id: binary_sensor.living_room_occupied
        to: 'on'
      - platform: state
        entity_id: sensor.light_mode
        to: 'normal'
      - platform: state
        entity_id: sensor.light_mode
        to: 'evening'
      - platform: state
        entity_id: sensor.light_mode
        to: 'full'
    condition:
      - condition: state
        entity_id: binary_sensor.living_room_occupied
        state: 'on'
      - condition: state
        entity_id: binary_sensor.living_room_occupancy_automation
        state: 'on'
      - condition: state
        entity_id: input_select.harmony
        state: 'PowerOff'
    action:
      - service: script.turn_on
        data_template:
          entity_id: script.scene_living_room_{{ states('sensor.light_mode') }}

  - alias: Living room TV on
    id: c4aac76a-3987-410c-904a-0da30579a2fc
    trigger:
      - platform: state
        entity_id: input_select.harmony
        to: 'TV'
      - platform: state
        entity_id: input_select.harmony
        to: 'Apple TV'
      - platform: state
        entity_id: input_select.harmony
        to: 'Music'
    condition:
      - condition: state
        entity_id: input_boolean.everyone_asleep
        state: 'off'
      - condition: state
        entity_id: binary_sensor.living_room_occupancy_automation
        state: 'on'
    action:
      - service: script.turn_on
        data_template:
          entity_id: >-
            {% if (is_state('input_select.harmony', 'TV') or is_state('input_select.harmony', 'Apple TV')) and is_state('sensor.light_mode', 'normal') %}
            script.scene_living_room_tv
            {% elif (is_state('input_select.harmony', 'TV') or is_state('input_select.harmony', 'Apple TV')) and is_state('sensor.light_mode', 'evening') %}
            script.scene_living_room_tv
            {% elif (is_state('input_select.harmony', 'TV') or is_state('input_select.harmony', 'Apple TV')) and is_state('sensor.light_mode', 'bright') %}
            script.scene_living_room_tv_only
            {% elif is_state('input_select.harmony', 'Music') and is_state('sensor.light_mode', 'normal') %}
            script.scene_living_room_music
            {% elif is_state('input_select.harmony', 'Music') and is_state('sensor.light_mode', 'evening') %}
            script.scene_living_room_music
            {% elif is_state('input_select.harmony', 'Music') and is_state('sensor.light_mode', 'bright') %}
            script.scene_living_room_music_only
            {% else %}
            script.scene_living_room_{{ states('sensor.light_mode') }}
            {% endif %}

  - alias: Living room TV off
    id: 46f8e97e-d7ea-407a-8ee9-5cb4f2ef6c99
    trigger:
      - platform: state
        entity_id: input_select.harmony
        to: 'PowerOff'
    condition:
      - condition: state
        entity_id: input_boolean.everyone_asleep
        state: 'off'
      - condition: state
        entity_id: binary_sensor.living_room_occupancy_automation
        state: 'on'
    action:
      - service: script.turn_on
        data_template:
          entity_id: script.scene_living_room_{{ states('sensor.light_mode') }}
