automation:
  - alias: Hallway lights idle
    id: b2111220-3e70-4e8c-b431-5b536219f698
    trigger:
      - platform: state
        entity_id: binary_sensor.hallway_occupied
        to: 'off'
      - platform: state
        entity_id: sensor.light_mode
    condition:
      - condition: state
        entity_id: binary_sensor.hallway_occupied
        state: 'off'
      - condition: state
        entity_id: binary_sensor.hallway_occupancy_automation
        state: 'on'
    action:
      - service: script.turn_on
        data_template:
          entity_id: script.scene_hallway_{{ state_attr('sensor.light_mode', 'off_mode') }}

  - alias: Hallway lights occupied
    id: 62fa7f2a-8273-4b27-8eda-25cb770ac20c
    trigger:
      - platform: state
        entity_id: binary_sensor.hallway_occupied
        to: 'on'
      - platform: state
        entity_id: sensor.light_mode
        to: 'normal'
      - platform: state
        entity_id: sensor.light_mode
        to: 'evening'
      - platform: state
        entity_id: sensor.light_mode
        to: 'full'
    condition:
      - condition: state
        entity_id: binary_sensor.hallway_occupied
        state: 'on'
      - condition: state
        entity_id: binary_sensor.hallway_occupancy_automation
        state: 'on'
    action:
      - service: script.turn_on
        data_template:
          entity_id: script.scene_hallway_{{ states('sensor.light_mode') }}
