automation:
  - alias: Living room lights idle
    trigger:
      - platform: state
        entity_id: input_boolean.living_room_occupied
        to: 'off'
      - platform: state
        entity_id: sensor.light_mode
      - platform: state
        entity_id: input_select.harmony
        to: 'PowerOff'
    condition:
      - condition: state
        entity_id: input_boolean.living_room_occupied
        state: 'off'
      - condition: state
        entity_id: input_boolean.living_room_occupancy_automation
        state: 'on'
      - condition: state
        entity_id: input_select.harmony
        state: 'PowerOff'
    action:
      - service: script.turn_on
        data_template:
          entity_id: script.scene_living_room_{{ state_attr('sensor.light_mode', 'off_mode') }}

  - alias: Living room lights occupied
    trigger:
      - platform: state
        entity_id: input_boolean.living_room_occupied
        to: 'on'
      - platform: state
        entity_id: sensor.light_mode
        to: 'normal'
      - platform: state
        entity_id: sensor.light_mode
        to: 'evening'
      - platform: state
        entity_id: sensor.light_mode
        to: 'full'
      - platform: state
        entity_id: input_select.harmony
        to: 'PowerOff'
    condition:
      - condition: state
        entity_id: input_boolean.living_room_occupied
        state: 'on'
      - condition: state
        entity_id: input_boolean.living_room_occupancy_automation
        state: 'on'
      - condition: state
        entity_id: input_select.harmony
        state: 'PowerOff'
    action:
      - service: script.turn_on
        data_template:
          entity_id: script.scene_living_room_{{ states('sensor.light_mode') }}

  - alias: Living room TV on
    trigger:
      - platform: state
        entity_id: input_select.harmony
        to: 'TV'
      - platform: state
        entity_id: input_select.harmony
        to: 'Apple TV'
      - platform: state
        entity_id: input_select.harmony
        to: 'Music'
    condition:
      - condition: state
        entity_id: input_boolean.everyone_asleep
        state: 'off'
    action:
      - service: script.turn_on
        data_template:
          entity_id: >-
            {% if (is_state('input_select.harmony', 'TV') or is_state('input_select.harmony', 'Apple TV')) and is_state('sensor.light_mode', 'normal') %}
            script.scene_living_room_tv
            {% elif (is_state('input_select.harmony', 'TV') or is_state('input_select.harmony', 'Apple TV')) and is_state('sensor.light_mode', 'evening') %}
            script.scene_living_room_tv
            {% elif (is_state('input_select.harmony', 'TV') or is_state('input_select.harmony', 'Apple TV')) and is_state('sensor.light_mode', 'bright') %}
            script.scene_living_room_tv_only
            {% elif is_state('input_select.harmony', 'Music') and is_state('sensor.light_mode', 'normal') %}
            script.scene_living_room_music
            {% elif is_state('input_select.harmony', 'Music') and is_state('sensor.light_mode', 'evening') %}
            script.scene_living_room_music
            {% elif is_state('input_select.harmony', 'Music') and is_state('sensor.light_mode', 'bright') %}
            script.scene_living_room_music_only
            {% else %}
            script.scene_living_room_{{ states('sensor.light_mode') }}
            {% endif %}
