automation:
  - alias: Bedroom lights idle
    id: 1f5b223e-7d8f-4ccf-bf0c-2a770fefcf96
    trigger:
      - platform: state
        entity_id: binary_sensor.bedroom_occupied
        to: 'off'
      - platform: state
        entity_id: sensor.light_mode
    condition:
      - condition: state
        entity_id: binary_sensor.bedroom_occupied
        state: 'off'
      - condition: state
        entity_id: input_boolean.bedroom_occupancy_automation
        state: 'on'
    action:
      - service: script.turn_on
        data_template:
          entity_id: script.scene_bedroom_{{ state_attr('sensor.light_mode', 'off_mode') }}

  - alias: Bedroom lights occupied
    id: 8b3577c0-c303-41cc-90bd-40fc9e988410
    trigger:
      - platform: state
        entity_id: binary_sensor.bedroom_occupied
        to: 'on'
      - platform: state
        entity_id: sensor.light_mode
        to: 'normal'
      - platform: state
        entity_id: sensor.light_mode
        to: 'evening'
      - platform: state
        entity_id: sensor.light_mode
        to: 'full'
    condition:
      - condition: state
        entity_id: binary_sensor.bedroom_occupied
        state: 'on'
      - condition: state
        entity_id: input_boolean.bedroom_occupancy_automation
        state: 'on'
    action:
      - service: script.turn_on
        data_template:
          entity_id: script.scene_bedroom_{{ states('sensor.light_mode') }}

  - alias: Bedroom lights sleep
    id: e0bcf4be-e10c-49c9-bfed-8e0263c83066
    trigger:
      - platform: state
        entity_id: input_boolean.johnny_asleep
        to: 'on'
      - platform: state
        entity_id: input_boolean.kajsa_asleep
        to: 'on'
    action:
      - service: script.turn_on
        entity_id: script.scene_bedroom_off

  - alias: Bedroom lights sleep off
    id: f4e6a694-bebf-4634-8238-8ff92334b751
    trigger:
      - platform: state
        entity_id: input_boolean.johnny_asleep
        to: 'off'
      - platform: state
        entity_id: input_boolean.kajsa_asleep
        to: 'off'
    condition:
      - condition: state
        entity_id: input_boolean.johnny_asleep
        state: 'off'
      - condition: state
        entity_id: input_boolean.kajsa_asleep
        state: 'off'
    action:
      - service: script.turn_on
        data_template:
          entity_id: script.scene_bedroom_{{ states('sensor.light_mode') }}
