automation:
  - alias: Bathroom lights idle
    id: 4c728cce-f061-4c5a-9fa8-ce64e5f9e725
    trigger:
      - platform: state
        entity_id: input_boolean.bathroom_occupied
        to: 'off'
      - platform: state
        entity_id: sensor.light_mode
    condition:
      - condition: state
        entity_id: input_boolean.bathroom_occupied
        state: 'off'
      - condition: state
        entity_id: input_boolean.bathroom_occupancy_automation
        state: 'on'
    action:
      - service: script.turn_on
        data_template:
          entity_id: script.scene_bathroom_{{ state_attr('sensor.light_mode', 'off_mode') }}

  - alias: Bathroom lights occupied
    id: 725ea4f5-2cca-4f38-ad55-2164a50877aa
    trigger:
      - platform: state
        entity_id: input_boolean.bathroom_occupied
        to: 'on'
      - platform: state
        entity_id: sensor.light_mode
        to: 'normal'
      - platform: state
        entity_id: sensor.light_mode
        to: 'evening'
      - platform: state
        entity_id: sensor.light_mode
        to: 'full'
    condition:
      - condition: state
        entity_id: input_boolean.bathroom_occupied
        state: 'on'
      - condition: state
        entity_id: input_boolean.bathroom_occupancy_automation
        state: 'on'
    action:
      - service: script.turn_on
        data_template:
          entity_id: script.scene_bathroom_{{ states('sensor.light_mode') }}
