automation:
  - alias: Kitchen lights idle
    trigger:
      - platform: state
        entity_id: input_boolean.kitchen_occupied
        to: 'off'
      - platform: state
        entity_id: sensor.light_mode
    condition:
      - condition: state
        entity_id: input_boolean.kitchen_occupied
        state: 'off'
      - condition: state
        entity_id: input_boolean.kitchen_occupancy_automation
        state: 'on'
    action:
      - service: script.turn_on
        data_template:
          entity_id: script.scene_kitchen_{{ state_attr('sensor.light_mode', 'off_mode') }}

  - alias: Kitchen lights occupied
    trigger:
      - platform: state
        entity_id: input_boolean.kitchen_occupied
        to: 'on'
      - platform: state
        entity_id: sensor.light_mode
        to: 'normal'
      - platform: state
        entity_id: sensor.light_mode
        to: 'evening'
      - platform: state
        entity_id: sensor.light_mode
        to: 'full'
    condition:
      - condition: state
        entity_id: input_boolean.kitchen_occupied
        state: 'on'
      - condition: state
        entity_id: input_boolean.kitchen_occupancy_automation
        state: 'on'
    action:
      - service: script.turn_on
        data_template:
          entity_id: script.scene_kitchen_{{ states('sensor.light_mode') }}
