automation:
  - alias: Office lights idle
    id: 8c4d484a-ffb9-4804-b016-2b80a0bc433e
    trigger:
      - platform: state
        entity_id: binary_sensor.office_occupied
        to: 'off'
      - platform: state
        entity_id: sensor.light_mode
    condition:
      - condition: state
        entity_id: binary_sensor.office_occupied
        state: 'off'
      - condition: state
        entity_id: input_boolean.office_occupancy_automation
        state: 'on'
    action:
      - service: script.turn_on
        data_template:
          entity_id: script.scene_office_{{ state_attr('sensor.light_mode', 'off_mode') }}

  - alias: Office lights occupied
    id: a362c710-e1eb-4e13-8be7-a178aa22880c
    trigger:
      - platform: state
        entity_id: binary_sensor.office_occupied
        to: 'on'
      - platform: state
        entity_id: sensor.light_mode
        to: 'normal'
      - platform: state
        entity_id: sensor.light_mode
        to: 'evening'
      - platform: state
        entity_id: sensor.light_mode
        to: 'full'
    condition:
      - condition: state
        entity_id: binary_sensor.office_occupied
        state: 'on'
      - condition: state
        entity_id: input_boolean.office_occupancy_automation
        state: 'on'
    action:
      - service: script.turn_on
        data_template:
          entity_id: script.scene_office_{{ states('sensor.light_mode') }}

  - alias: Office video meeting on
    id: 5fc5ecd4-e275-423b-bbd4-9c3abc13d80a
    trigger:
      - platform: state
        entity_id: binary_sensor.stk_jchadda_camera_in_use
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.office_occupancy_automation
        state: 'on'
    action:
      - service: light.turn_on
        data:
          entity_id: light.office_monitor
          brightness_pct: 100
          kelvin: 5500

  - alias: Office video meeting off
    id: 1d291257-79fc-4e6f-94a2-4845aa466798
    trigger:
      - platform: state
        entity_id: binary_sensor.stk_jchadda_camera_in_use
        to: 'off'
    condition:
      - condition: state
        entity_id: input_boolean.office_occupancy_automation
        state: 'on'
    action:
      - service: adaptive_lighting.set_manual_control
        data:
          entity_id: switch.adaptive_lighting_main
          manual_control: false
          lights:
            - light.office_monitor

  - alias: Office lights sleep
    id: 988ae927-3368-4479-8391-8ef5c340d7ce
    trigger:
      - platform: state
        entity_id: input_boolean.guest_asleep
        to: 'on'
    action:
      - service: script.turn_on
        entity_id: script.scene_office_off

  - alias: Office lights sleep off
    id: 14a467b4-9fe9-4ce2-8772-7080ab58d2c8
    trigger:
      - platform: state
        entity_id: input_boolean.guest_asleep
        to: 'off'
    action:
      - service: script.turn_on
        data_template:
          entity_id: script.scene_office_{{ states('sensor.light_mode') }}
