automation:
  - alias: Bedroom lights idle
    trigger:
      - platform: state
        entity_id: input_boolean.bedroom_occupied
        to: 'off'
      - platform: state
        entity_id: sensor.light_mode
      - platform: state
        entity_id: input_boolean.johnny_asleep
        to: 'off'
      - platform: state
        entity_id: input_boolean.kajsa_asleep
        to: 'off'
    condition:
      - condition: state
        entity_id: input_boolean.bedroom_occupied
        state: 'off'
      - condition: state
        entity_id: input_boolean.bedroom_occupancy_automation
        state: 'on'
      - condition: state
        entity_id: input_boolean.johnny_asleep
        state: 'off'
      - condition: state
        entity_id: input_boolean.kajsa_asleep
        state: 'off'
    action:
      - service: script.turn_on
        data_template:
          entity_id: script.scene_bedroom_{{ state_attr('sensor.light_mode', 'off_mode') }}

  - alias: Bedroom lights occupied
    trigger:
      - platform: state
        entity_id: input_boolean.bedroom_occupied
        to: 'on'
      - platform: state
        entity_id: sensor.light_mode
        to: 'normal'
      - platform: state
        entity_id: sensor.light_mode
        to: 'evening'
      - platform: state
        entity_id: sensor.light_mode
        to: 'full'
      - platform: state
        entity_id: input_boolean.johnny_asleep
        to: 'off'
      - platform: state
        entity_id: input_boolean.kajsa_asleep
        to: 'off'
    condition:
      - condition: state
        entity_id: input_boolean.bedroom_occupied
        state: 'on'
      - condition: state
        entity_id: input_boolean.bedroom_occupancy_automation
        state: 'on'
      - condition: state
        entity_id: input_boolean.johnny_asleep
        state: 'off'
      - condition: state
        entity_id: input_boolean.kajsa_asleep
        state: 'off'
    action:
      - service: script.turn_on
        data_template:
          entity_id: script.scene_bedroom_{{ states('sensor.light_mode') }}

  - alias: Bedroom lights sleep
    trigger:
      - platform: state
        entity_id: input_boolean.johnny_asleep
        to: 'on'
      - platform: state
        entity_id: input_boolean.kajsa_asleep
        to: 'on'
    action:
      - service: script.turn_on
        entity_id: script.scene_bedroom_off
