automation:
  - alias: Kitchen lights idle
    id: 0141f12b-a6a0-4a76-b702-45cef40905b9
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_occupied
        to: 'off'
      - platform: state
        entity_id: sensor.light_mode
    condition:
      - condition: state
        entity_id: binary_sensor.kitchen_occupied
        state: 'off'
      - condition: state
        entity_id: input_boolean.kitchen_occupancy_automation
        state: 'on'
    action:
      - service: script.turn_on
        data_template:
          entity_id: script.scene_kitchen_{{ state_attr('sensor.light_mode', 'off_mode') }}

  - alias: Kitchen lights occupied
    id: fc18f98a-2b1b-4c4c-8e42-650968011c30
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_occupied
        to: 'on'
      - platform: state
        entity_id: sensor.light_mode
        to: 'normal'
      - platform: state
        entity_id: sensor.light_mode
        to: 'evening'
      - platform: state
        entity_id: sensor.light_mode
        to: 'full'
    condition:
      - condition: state
        entity_id: binary_sensor.kitchen_occupied
        state: 'on'
      - condition: state
        entity_id: input_boolean.kitchen_occupancy_automation
        state: 'on'
    action:
      - service: script.turn_on
        data_template:
          entity_id: script.scene_kitchen_{{ states('sensor.light_mode') }}
