automation:
  - alias: Leas lights idle
    id: 1e66b3fe-785e-4039-a1b5-93c526e83d6c
    trigger:
      - platform: state
        entity_id: binary_sensor.leas_occupied
        to: 'off'
      - platform: state
        entity_id: sensor.light_mode
    condition:
      - condition: state
        entity_id: binary_sensor.leas_occupied
        state: 'off'
      - condition: state
        entity_id: input_boolean.leas_occupancy_automation
        state: 'on'
    action:
      - service: script.turn_on
        data_template:
          entity_id: script.scene_leas_{{ state_attr('sensor.light_mode', 'off_mode') }}

  - alias: Leas lights occupied
    id: 90ab0af2-cec8-42c6-b7fb-27725e361b58
    trigger:
      - platform: state
        entity_id: binary_sensor.leas_occupied
        to: 'on'
      - platform: state
        entity_id: sensor.light_mode
        to: 'normal'
      - platform: state
        entity_id: sensor.light_mode
        to: 'evening'
      - platform: state
        entity_id: sensor.light_mode
        to: 'full'
    condition:
      - condition: state
        entity_id: binary_sensor.leas_occupied
        state: 'on'
      - condition: state
        entity_id: input_boolean.leas_occupancy_automation
        state: 'on'
    action:
      - service: script.turn_on
        data_template:
          entity_id: script.scene_leas_{{ states('sensor.light_mode') }}

  - alias: Leas lights sleep
    id: 01637112-1968-4fac-b934-20114b5e4d6c
    trigger:
      - platform: state
        entity_id: input_boolean.lea_asleep
        to: 'on'
    action:
      - service: script.turn_on
        entity_id: script.scene_leas_off
