automation:
  - alias: Dining Room lights idle
    id: b979f617-a463-4d12-aa3f-ff3c26a2f320
    trigger:
      - platform: state
        entity_id: binary_sensor.dining_room_occupied
        to: 'off'
      - platform: state
        entity_id: sensor.light_mode
    condition:
      - condition: state
        entity_id: binary_sensor.dining_room_occupied
        state: 'off'
      - condition: state
        entity_id: input_boolean.dining_room_occupancy_automation
        state: 'on'
    action:
      - service: script.turn_on
        data_template:
          entity_id: script.scene_dining_room_{{ state_attr('sensor.light_mode', 'off_mode') }}

  - alias: Dining_Room lights occupied
    id: 4dff0b66-aab3-428d-903c-9fc12154c277
    trigger:
      - platform: state
        entity_id: binary_sensor.dining_room_occupied
        to: 'on'
      - platform: state
        entity_id: sensor.light_mode
        to: 'normal'
      - platform: state
        entity_id: sensor.light_mode
        to: 'evening'
      - platform: state
        entity_id: sensor.light_mode
        to: 'full'
    condition:
      - condition: state
        entity_id: binary_sensor.dining_room_occupied
        state: 'on'
      - condition: state
        entity_id: input_boolean.dining_room_occupancy_automation
        state: 'on'
    action:
      - service: script.turn_on
        data_template:
          entity_id: script.scene_dining_room_{{ states('sensor.light_mode') }}
