default_view:
  view: yes
  icon: mdi:home
  entities:
    - group.alarm
    - group.household
    - group.house_guests
    - group.interior_lights
    - group.scenes
    - group.indoor_temperature
    - group.indoor_humidity
    - group.indoor_motion
    - group.perimeter

masterbed:
  name: Master Bedroom
  view: yes
  icon: mdi:hotel
  entities:
    - group.bedroom_lights
    - group.bedroom
    - group.sleep_status

living:
  name: Living Room
  view: yes
  icon: mdi:sofa
  entities:
    - group.living_room_lights
    - group.living_room
    - vacuum.greta
    - media_player.samsung_tv_remote
    - media_player.spotify
    - media_player.xboxone
    - media_player.tv_ue55f8000
    - media_player.living_room_speakers

balc:
  name: Balcony
  view: yes
  icon: mdi:door-open
  entities:
    group.balcony

bath:
  name: Bathroom
  view: yes
  icon: mdi:hot-tub
  entities:
    - group.bathroom

clos:
  name: Closet
  view: yes
  icon: mdi:hanger
  entities:
    - group.closet
    - group.ups_status
    - group.zwave

hall:
  name: Hallway
  view: yes
  icon: mdi:cube-unfolded
  entities:
    - group.hallway_lights
    - light.hallway_ceiling_lamp
    - group.hallway

kitch:
  name: Kitchen
  view: yes
  icon: mdi:stove
  entities:
    - group.kitchen_lights
    - group.kitchen

guestbed:
  name: Guest Bedroom
  view: yes
  icon: mdi:human-male-female
  entities:
    - group.guest_bedroom_lights
    - group.guest_bedroom
    - group.sleep_status

automation:
  name: Automation
  view: yes
  icon: mdi:robot
  entities:
    - group.automation_override
    - group.security_automation
    - group.motion_detection

security:
  name: Security
  view: yes
  icon: mdi:cctv
  entities:
    - group.alarm
    - group.hallway_camera
    - group.living_room_camera
    - group.perimeter
    - group.indoor_motion
    - group.water

weatherdash:
  name: Weather
  view: yes
  icon: mdi:weather-cloudy
  entities:
    - group.indoor_temperature
    - group.indoor_humidity
    - group.weather_summary
    - group.weather
