- platform: template
  sensors:
    light_mode:
      friendly_name: Light Mode
      value_template: >-
        {% if is_state('sun.sun', 'below_horizon') and now().hour < 23 and is_state('alarm_control_panel.alarm', 'armed_away') %}
        evening
        {% elif is_state('alarm_control_panel.alarm', 'armed_away') %}
        off
        {% elif is_state('input_boolean.everyone_asleep', 'on') %}
        night
        {% elif is_state('input_boolean.lights_full', 'on') %}
        full
        {% elif is_state('group.sleep_status', 'on') and now().hour >= 19  %}
        evening
        {% elif states('sensor.living_room_luminance')|float < 40 %}
        normal
        {% else %}
        off
        {% endif %}
      attribute_templates:
        off_mode: >-
          {% if is_state('sensor.light_mode', 'off') %}
          off
          {% else %}
          dim
          {% endif %}
