# Temporarily moved bedroom temperature sensor to closet
# for fan monitoring
- alias: Turn on ventilation fan
  trigger:
    - platform: numeric_state
      entity_id: sensor.closet_humidity
      below: 40
      for:
        minutes: 10
    - platform: numeric_state
      entity_id: sensor.closet_temperature
      above: 20
      for:
        minutes: 10
  condition:
    - condition: state
      entity_id: input_boolean.closet_ventilation_fan_automation
      state: 'on'
    - condition: state
      entity_id: switch.living_room_outlet
      state: 'off'
    - condition: numeric_state
      entity_id: sensor.closet_humidity
      below: 40
    - condition: numeric_state
      entity_id: sensor.closet_temperature
      above: 20
  action:
    - service: switch.turn_on
      entity_id: switch.living_room_outlet

- alias: Turn off ventilation fan
  trigger:
    - platform: numeric_state
      entity_id: sensor.closet_humidity
      above: 40
      for:
        minutes: 10
    - platform: numeric_state
      entity_id: sensor.closet_temperature
      below: 20
      for:
        minutes: 10
  condition:
    - condition: state
      entity_id: input_boolean.closet_ventilation_fan_automation
      state: 'on'
    - condition: state
      entity_id: switch.living_room_outlet
      state: 'on'
    - condition: numeric_state
      entity_id: sensor.closet_humidity
      above: 40
    - condition: numeric_state
      entity_id: sensor.closet_temperature
      below: 20
  action:
    - service: switch.turn_off
      entity_id: switch.living_room_outlet
