automation:
  - alias: Kitchen occupied
    id: b1db264d-e7d4-414e-be11-0394535f26e3
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_motion
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.kitchen_occupancy_automation
        state: 'on'
    action:
      - service: timer.cancel
        entity_id: timer.kitchen_lights
      - service: input_boolean.turn_on
        entity_id: input_boolean.kitchen_occupied

  - alias: Kitchen start idle timer
    id: 463d05c2-d6dd-4c06-9e40-c65ccd1ce803
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_motion
        to: 'off'
    condition:
      - condition: or
        conditions:
          - condition: state
            entity_id: timer.kitchen_lights
            state: 'idle'
          - condition: state
            entity_id: timer.kitchen_lights
            state: 'active'
    action:
      - service: timer.start
        entity_id: timer.kitchen_lights

  - alias: Kitchen idle
    id: 48b17165-ec2a-4d71-9b26-d61298dfcb57
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.kitchen_lights
    condition:
      - condition: state
        entity_id: input_boolean.kitchen_occupancy_automation
        state: 'on'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.kitchen_occupied

  - alias: Disable kitchen motion on button click
    id: b3a60494-bd68-44a8-acaa-f2f2a5d02dbf
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: kitchen_dimmer
          event: 4003
    condition:
      - condition: state
        entity_id: input_boolean.kitchen_occupancy_automation
        state: 'on'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.kitchen_occupancy_automation

  - alias: Enable kitchen motion
    id: 2b8eba9f-7240-4d7a-8ace-1d5644fbaba9
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_motion
        to: 'off'
        for: '01:00:00'
      - platform: event
        event_type: deconz_event
        event_data:
          id: kitchen_dimmer
          event: 1003
    condition:
      - condition: state
        entity_id: input_boolean.kitchen_occupancy_automation
        state: 'off'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.kitchen_occupancy_automation
      - service: script.turn_on
        data_template:
          entity_id: script.scene_kitchen_{{ states('sensor.light_mode') }}
