automation:
  - alias: Bathroom occupied
    id: 8080a5bc-4b2b-46dc-bd54-ac7d241bca3c
    trigger:
      - platform: state
        entity_id: binary_sensor.bathroom_motion
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.bathroom_occupancy_automation
        state: 'on'
      - condition: or
        conditions:
          - condition: state
            entity_id: timer.bathroom_lights
            state: 'idle'
          - condition: state
            entity_id: timer.bathroom_lights
            state: 'active'
    action:
      - service: timer.cancel
        entity_id: timer.bathroom_lights
      - service: input_boolean.turn_on
        entity_id: input_boolean.bathroom_occupied

  - alias: Bathroom start idle timer
    id: f24bc852-cfa7-40e4-b58c-7ca84255cc68
    trigger:
      - platform: state
        entity_id: binary_sensor.bathroom_motion
        to: 'off'
    condition:
      - condition: or
        conditions:
          - condition: state
            entity_id: timer.bathroom_lights
            state: 'idle'
          - condition: state
            entity_id: timer.bathroom_lights
            state: 'active'
    action:
      - service: timer.start
        entity_id: timer.bathroom_lights

  - alias: Bathroom idle
    id: ba2e09c5-086d-49f7-9a69-fbef3a73ff4a
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.bathroom_lights
    condition:
      - condition: state
        entity_id: input_boolean.bathroom_occupancy_automation
        state: 'on'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.bathroom_occupied

  - alias: Bathroom pause timer on high moisture
    id: d7fe70f7-a2a5-4509-a25d-ca418775e9f8
    trigger:
      - platform: numeric_state
        entity_id: sensor.bathroom_humidity
        above: 50
    action:
      - service: timer.start
        entity_id: timer.bathroom_lights
      - service: timer.pause
        entity_id: timer.bathroom_lights

  - alias: Bathroom resume timer on low moisture
    id: ca0d3ded-a005-4a5d-8a8a-9f565cab2be6
    trigger:
      - platform: numeric_state
        entity_id: sensor.bathroom_humidity
        below: 50
    condition:
      - condition: state
        entity_id: timer.bathroom_lights
        state: 'paused'
    action:
      - service: timer.cancel
        entity_id: timer.bathroom_lights

  - alias: Bathroom pause timer on door closed
    id: 49c098f7-0f0e-48ee-874d-e4c2cd4cf197
    trigger:
      - platform: state
        entity_id: binary_sensor.bathroom_motion
        to: 'on'
    condition:
      - condition: state
        entity_id: binary_sensor.bathroom_door
        state: 'off'
    action:
      - service: timer.start
        entity_id: timer.bathroom_lights
      - service: timer.pause
        entity_id: timer.bathroom_lights

  - alias: Bathroom resume timer on door open
    id: f52d7377-692c-4de5-a84a-6cd1e7ff166e
    trigger:
      - platform: state
        entity_id: binary_sensor.bathroom_door
        to: 'on'
    condition:
      - condition: state
        entity_id: timer.bathroom_lights
        state: 'paused'
    action:
      - service: timer.cancel
        entity_id: timer.bathroom_lights

  - alias: Disable bathroom motion on button click
    id: 0498e667-a483-4a27-869c-dd5feadfd709
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: bathroom_dimmer
          event: 4003
    condition:
      - condition: state
        entity_id: input_boolean.bathroom_occupancy_automation
        state: 'on'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.bathroom_occupancy_automation

  - alias: Enable bathroom motion
    id: 6f46d69b-f07d-4479-b397-5468effe015e
    trigger:
      - platform: state
        entity_id: binary_sensor.bathroom_motion
        to: 'off'
        for: '01:00:00'
      - platform: event
        event_type: deconz_event
        event_data:
          id: bathroom_dimmer
          event: 1003
    condition:
      - condition: state
        entity_id: input_boolean.bathroom_occupancy_automation
        state: 'off'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.bathroom_occupancy_automation
      - service: script.turn_on
        data_template:
          entity_id: script.scene_bathroom_{{ states('sensor.light_mode') }}
