automation:
  - alias: Living room occupied
    trigger:
      - platform: state
        entity_id: binary_sensor.living_room_motion_sensor
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.living_room_occupancy_automation
        state: 'on'
    action:
      - service: timer.cancel
        entity_id: timer.living_room_lights
      - service: input_boolean.turn_on
        entity_id: input_boolean.living_room_occupied

  - alias: Living room start idle timer
    trigger:
      - platform: state
        entity_id: binary_sensor.living_room_motion_sensor
        to: 'off'
    action:
      - service: timer.start
        entity_id: timer.living_room_lights

  - alias: Living room idle
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.living_room_lights
    condition:
      - condition: state
        entity_id: input_boolean.living_room_occupancy_automation
        state: 'on'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.living_room_occupied

  - alias: Disable living room motion on button click
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: living_room_dimmer
          event: 4003
    condition:
      - condition: state
        entity_id: input_boolean.living_room_occupancy_automation
        state: 'on'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.living_room_occupancy_automation

  - alias: Enable living room motion
    trigger:
      - platform: state
        entity_id: binary_sensor.living_room_motion_sensor
        to: 'off'
        for: '01:00:00'
      - platform: event
        event_type: deconz_event
        event_data:
          id: living_room_dimmer
          event: 1003
    condition:
      - condition: state
        entity_id: input_boolean.living_room_occupancy_automation
        state: 'off'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.living_room_occupancy_automation
      - service: script.turn_on
        data_template:
          entity_id: script.scene_living_room_{{ states('sensor.light_mode') }}
