automation:
  - alias: Bedroom occupied
    id: fe305138-78af-443e-a7b7-695201244635
    trigger:
      - platform: state
        entity_id: binary_sensor.bedroom_motion
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.bedroom_occupancy_automation
        state: 'on'
    action:
      - service: timer.cancel
        entity_id: timer.bedroom_lights
      - service: input_boolean.turn_on
        entity_id: input_boolean.bedroom_occupied

  - alias: Bedroom start idle timer
    id: 418a7fba-7123-473e-a1b2-29739c191e15
    trigger:
      - platform: state
        entity_id: binary_sensor.bedroom_motion
        to: 'off'
    action:
      - service: timer.start
        entity_id: timer.bedroom_lights

  - alias: Bedroom idle
    id: c3bb9f78-9792-41f9-ad3f-5a52029680e9
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.bedroom_lights
    condition:
      - condition: state
        entity_id: input_boolean.bedroom_occupancy_automation
        state: 'on'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.bedroom_occupied

  - alias: Disable bedroom motion on button click
    id: d3848152-6764-4c0e-8491-ebfe52bda41a
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: bedroom_dimmer
          event: 4003
    condition:
      - condition: state
        entity_id: input_boolean.bedroom_occupancy_automation
        state: 'on'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.bedroom_occupancy_automation

  - alias: Enable bedroom motion
    id: 254d8b44-344b-4a1f-94a0-9eed56cb2e29
    trigger:
      - platform: state
        entity_id: binary_sensor.bedroom_motion
        to: 'off'
        for: '01:00:00'
      - platform: event
        event_type: deconz_event
        event_data:
          id: bedroom_dimmer
          event: 1003
    condition:
      - condition: state
        entity_id: input_boolean.bedroom_occupancy_automation
        state: 'off'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.bedroom_occupancy_automation
      - service: script.turn_on
        data_template:
          entity_id: script.scene_bedroom_{{ states('sensor.light_mode') }}
