automation:
  - alias: Living room occupied
    id: d8cc01f0-0068-4c0a-936d-5e5975022c71
    trigger:
      - platform: state
        entity_id: binary_sensor.living_room_motion_sensor
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.living_room_occupancy_automation
        state: 'on'
    action:
      - service: timer.cancel
        entity_id: timer.living_room_lights
      - service: input_boolean.turn_on
        entity_id: input_boolean.living_room_occupied

  - alias: Living room start idle timer
    id: adcfa3bb-a9c4-4330-8c22-be28c8250f7c
    trigger:
      - platform: state
        entity_id: binary_sensor.living_room_motion_sensor
        to: 'off'
    action:
      - service: timer.start
        entity_id: timer.living_room_lights

  - alias: Living room idle
    id: 28508037-f269-4f8d-96d7-f3f6752a5831
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.living_room_lights
    condition:
      - condition: state
        entity_id: input_boolean.living_room_occupancy_automation
        state: 'on'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.living_room_occupied

  - alias: Disable living room motion on button click
    id: 5072937c-1825-4ce4-bcf3-f1c752f284da
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: living_room_dimmer
          event: 4003
    condition:
      - condition: state
        entity_id: input_boolean.living_room_occupancy_automation
        state: 'on'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.living_room_occupancy_automation

  - alias: Enable living room motion
    id: c7cb55ca-5451-4385-a68d-36fc6bcfe9f2
    trigger:
      - platform: state
        entity_id: binary_sensor.living_room_motion_sensor
        to: 'off'
        for: '01:00:00'
      - platform: event
        event_type: deconz_event
        event_data:
          id: living_room_dimmer
          event: 1003
    condition:
      - condition: state
        entity_id: input_boolean.living_room_occupancy_automation
        state: 'off'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.living_room_occupancy_automation
      - service: script.turn_on
        data_template:
          entity_id: script.scene_living_room_{{ states('sensor.light_mode') }}
