- alias: Balcony lights on
  trigger:
    - platform: state
      entity_id: sensor.light_mode
      to: 'normal'
    - platform: state
      entity_id: sensor.light_mode
      to: 'evening'
  action:
    - service: script.turn_on
      entity_id: script.scene_balcony_normal

- alias: Balcony lights off
  trigger:
    - platform: state
      entity_id: sensor.light_mode
      to: 'off'
    - platform: state
      entity_id: sensor.light_mode
      to: 'night'
    - platform: state
      entity_id: sensor.light_mode
      to: 'bright'
    - platform: state
      entity_id: sensor.light_mode
      to: 'full'
  action:
    - service: script.turn_on
      entity_id: script.scene_balcony_off
