- alias: Balcony lights on
  trigger:
    - platform: state
      entity_id: input_boolean.lights_needed
      to: 'on'
  action:
    - service: script.turn_on
      entity_id: script.scene_balcony_normal

- alias: Balcony lights off
  trigger:
    platform: state
    entity_id: input_boolean.lights_needed
    to: 'off'
  action:
    - service: script.turn_on
      entity_id: script.scene_balcony_off
