apcupsd:
  host: !secret apcupsd_host

sensor:
  - platform: apcupsd
    resources:
      - status
      - linev
      - loadpct
      - bcharge
      - timeleft
      - itemp
      - lotrans
      - hitrans
      - lastxfer
      - numxfers
      - xoffbatt

binary_sensor:
  - platform: apcupsd
