group:
  Indoor Motion:
    - binary_sensor.bedroom_motion
    - binary_sensor.living_room_motion_sensor
    - binary_sensor.hallway_motion
    - binary_sensor.bathroom_motion
    - binary_sensor.kitchen_motion
    - binary_sensor.guest_bedroom_motion

automation:
  - alias: Check if ok if no movement but home
    trigger:
      - platform: state
        entity_id: group.indoor_motion
        to: 'off'
        for: '02:00:00'
    condition:
      - condition: state
        entity_id: group.household
        state: 'home'
        for: '02:00:00'
      - condition: state
        entity_id: input_boolean.kajsa_asleep
        state: 'off'
        for: '02:00:00'
      - condition: state
        entity_id: input_boolean.johnny_asleep
        state: 'off'
        for: '02:00:00'
    action:
      - service: notify.all_phones
        data:
          title: "Someone home but no movement"
          message: "No movement detected for 2 hours! Call and make sure that they are ok."
