input_select:
  harmony:
    name: Harmony
    icon: mdi:monitor
    options:
      - PowerOff
      - TV
      - Apple TV
      - Music

automation:
  - alias: Set Harmony activity using input_select
    id: 711d2e2a-2c60-4e88-b6eb-5819b60d2c9b
    trigger:
      platform: state
      entity_id: input_select.harmony
    action:
      service: remote.turn_on
      entity_id: remote.living_room
      data_template:
        activity: >
          {% if is_state("input_select.harmony", "TV") %}
            43340168
          {% elif is_state("input_select.harmony", "Apple TV") %}
            42807286
          {% elif is_state("input_select.harmony", "Music") %}
            29561682
          {% else %}
            -1
          {% endif %}

  - alias: Update Harmony input_select
    id: d02ebd42-b159-41cd-b8a8-b171b9729b89
    trigger:
      platform: state
      entity_id: remote.living_room
    action:
      service: input_select.select_option
      data_template:
        entity_id: input_select.harmony
        option: "{{ state_attr('remote.living_room', 'current_activity') }}"

  - alias: PowerOff Harmony when alarm is armed_away
    id: e7db3ade-4bd8-4b16-8296-b157be635682
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm
        to: 'armed_away'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.harmony
          option: 'PowerOff'

  - alias: Turn off TV automatically
    id: aba1e093-6571-41ea-b734-7a5ae1db3ac8
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm
        to: 'armed_away'
      - platform: state
        entity_id: input_boolean.everyone_asleep
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.music_automation
        state: 'on'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.harmony
          option: 'PowerOff'
