homeassistant:
  customize_glob:
    "script.scene_*":
      can_cancel: false
    "script.scene_*_off":
      icon: mdi:lightbulb-off-outline
    "script.scene_*_dim":
      icon: mdi:lightbulb-outline
    "script.scene_*_normal":
      icon: mdi:lightbulb-on-outline
    "script.scene_*_evening":
      icon: mdi:weather-night
    "script.scene_*_night":
      icon: mdi:sleep
    "script.scene_*_bright":
      icon: mdi:weather-sunny
    "script.scene_*_full":
      icon: mdi:lightbulb-on

input_boolean:
  lights_full:
    name: Lights Full
    icon: mdi:lightbulb-on-outline

sensor:
  - platform: template
    sensors:
      light_mode:
        friendly_name: Light Mode
        value_template: >-
          {% if is_state('sun.sun', 'below_horizon') and now().hour >= 7 and now().hour <= 22 and is_state('alarm_control_panel.alarm', 'armed_away') %}
          evening
          {% elif is_state('alarm_control_panel.alarm', 'armed_away') %}
          off
          {% elif is_state('input_boolean.everyone_asleep', 'on') %}
          night
          {% elif is_state('input_boolean.lights_full', 'on') %}
          full
          {% elif (is_state('sun.sun', 'below_horizon') and now().hour >= 20) or now().hour >= 20 %}
          evening
          {% elif states('sensor.living_room_motion_illuminance')|float <= 150 %}
          normal
          {% else %}
          bright
          {% endif %}
        attribute_templates:
          off_mode: >-
            {% if is_state('sensor.light_mode', 'off') or is_state('sensor.light_mode', 'night') or is_state('sensor.light_mode', 'bright') %}
            off
            {% elif is_state('sensor.light_mode', 'evening') %}
            dim_evening
            {% else %}
            dim
            {% endif %}

automation:
  - alias: Turn on and off night lights
    id: b9da9c0a-0d2c-41fa-b468-611b9a729ac5
    trigger:
      - platform: state
        entity_id: input_boolean.everyone_asleep
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: input_boolean.everyone_asleep
                state: 'on'
            sequence:
              - service: switch.turn_on
                entity_id: switch.adaptive_lighting_sleep_mode_main
              - service: switch.turn_on
                entity_id: switch.adaptive_lighting_sleep_mode_brighter
          - conditions:
              - condition: state
                entity_id: input_boolean.everyone_asleep
                state: 'off'
            sequence:
              - service: switch.turn_off
                entity_id: switch.adaptive_lighting_sleep_mode_main
              - service: switch.turn_off
                entity_id: switch.adaptive_lighting_sleep_mode_brighter
