homeassistant:
  customize_glob:
    "script.scene_*":
      can_cancel: false
    "script.scene_*_off":
      icon: mdi:lightbulb-off-outline
    "script.scene_*_dim":
      icon: mdi:lightbulb-outline
    "script.scene_*_normal":
      icon: mdi:lightbulb-on-outline
    "script.scene_*_evening":
      icon: mdi:weather-night
    "script.scene_*_night":
      icon: mdi:sleep
    "script.scene_*_bright":
      icon: mdi:weather-sunny
    "script.scene_*_full":
      icon: mdi:lightbulb-on

input_boolean:
  lights_full:
    name: Lights Full
    icon: mdi:lightbulb-on-outline

input_select:
  scene:
    name: Scene
    icon: mdi:circle-expand
    initial: Choose
    options:
      - Choose
      - Bedroom Off
      - Bedroom Dim
      - Bedroom Normal
      - Bedroom Evening
      - Bedroom Full
      - Bedroom Bright
      - Living Room Off
      - Living Room Dim
      - Living Room Normal
      - Living Room Evening
      - Living Room Night
      - Living Room Full
      - Living Room Bright
      - Living Room TV
      - Living Room TV Only
      - Living Room Music
      - Living Room Music Only
      - Balcony Off
      - Balcony Normal
      - Balcony Bright
      - Bathroom Off
      - Bathroom Dim
      - Bathroom Normal
      - Bathroom Evening
      - Bathroom Night
      - Bathroom Full
      - Bathroom Bright
      - Hallway Off
      - Hallway Dim
      - Hallway Normal
      - Hallway Evening
      - Hallway Night
      - Hallway Full
      - Hallway Bright
      - Kitchen Off
      - Kitchen Dim
      - Kitchen Normal
      - Kitchen Evening
      - Kitchen Night
      - Kitchen Full
      - Kitchen Bright
      - Guest Bedroom Off
      - Guest Bedroom Dim
      - Guest Bedroom Normal
      - Guest Bedroom Evening
      - Guest Bedroom Full
      - Guest Bedroom Bright
      - Home Off
      - Home Dim
      - Home Normal
      - Home Evening
      - Home Full

sensor:
  - platform: template
    sensors:
      light_mode:
        friendly_name: Light Mode
        value_template: >-
          {% if is_state('sun.sun', 'below_horizon') and now().hour >= 7 and now().hour <= 22 and is_state('alarm_control_panel.alarm', 'armed_away') %}
          evening
          {% elif is_state('alarm_control_panel.alarm', 'armed_away') %}
          off
          {% elif is_state('input_boolean.everyone_asleep', 'on') %}
          night
          {% elif is_state('input_boolean.lights_full', 'on') %}
          full
          {% elif (is_state('sun.sun', 'below_horizon') and now().hour >= 20) or now().hour >= 20 %}
          evening
          {% elif states('sensor.living_room_motion_illuminance')|float <= 50 %}
          normal
          {% else %}
          bright
          {% endif %}
        attribute_templates:
          off_mode: >-
            {% if is_state('sensor.light_mode', 'off') or is_state('sensor.light_mode', 'night') or is_state('sensor.light_mode', 'bright') %}
            off
            {% elif is_state('sensor.light_mode', 'evening') %}
            dim_evening
            {% else %}
            dim
            {% endif %}

automation:
  - alias: Activate chosen scene
    id: fc6d3e4f-cdc1-480d-af7e-ef75be4d5704
    trigger:
      - platform: state
        entity_id: input_select.scene
    action:
      - service: script.turn_on
        data_template:
          entity_id: script.scene_{{ states('input_select.scene')|lower|replace(" ", "_") }}
      - service: input_select.select_option
        data_template:
          entity_id: input_select.scene
          option: Choose
  - alias: Turn on and off night lights
    id: b9da9c0a-0d2c-41fa-b468-611b9a729ac5
    trigger:
      - platform: state
        entity_id: input_boolean.everyone_asleep
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: input_boolean.everyone_asleep
                state: 'on'
            sequence:
              - service: switch.turn_on
                entity_id: switch.adaptive_lighting_sleep_mode_main
              - service: switch.turn_on
                entity_id: switch.adaptive_lighting_sleep_mode_brighter
          - conditions:
              - condition: state
                entity_id: input_boolean.everyone_asleep
                state: 'off'
            sequence:
              - service: switch.turn_off
                entity_id: switch.adaptive_lighting_sleep_mode_main
              - service: switch.turn_off
                entity_id: switch.adaptive_lighting_sleep_mode_brighter
