input_boolean:
  bedroom_occupancy_automation:
    name: Bedroom Motion Detection
    icon: mdi:eye-outline
  living_room_occupancy_automation:
    name: Living Room Motion Detection
    icon: mdi:eye-outline
  bathroom_occupancy_automation:
    name: Bathroom Motion Detection
    icon: mdi:eye-outline
  hallway_occupancy_automation:
    name: Hallway Motion Detection
    icon: mdi:eye-outline
  kitchen_occupancy_automation:
    name: Kitchen Motion Detection
    icon: mdi:eye-outline
  office_occupancy_automation:
    name: Office Motion Detection
    icon: mdi:eye-outline
  leas_occupancy_automation:
    name: Leas Motion Detection
    icon: mdi:eye-outline
  claras_occupancy_automation:
    name: Claras Motion Detection
    icon: mdi:eye-outline
  entrance_occupancy_automation:
    name: Entrance Motion Detection
    icon: mdi:eye-outline
  dining_room_occupancy_automation:
    name: Dining Room Motion Detection
    icon: mdi:eye-outline
  parents_hallway_occupancy_automation:
    name: Parents Hallway Motion Detection
    icon: mdi:eye-outline
  kids_hallway_occupancy_automation:
    name: Kids Hallway Motion Detection
    icon: mdi:eye-outline

binary_sensor:
  - platform: template
    sensors:
      bedroom_occupied:
        friendly_name: Bedroom Occupied
        icon_template: mdi:walk
        value_template: >
          {{ is_state("input_boolean.bedroom_occupancy_automation", "on") and (
               is_state("binary_sensor.bedroom_motion_sensor", "on") or
               is_state("binary_sensor.working", "on")
             )
          }}
        delay_off: "00:10:00"

      living_room_occupied:
        friendly_name: Living Room Occupied
        icon_template: mdi:walk
        value_template: >
          {{ is_state("input_boolean.living_room_occupancy_automation", "on") and (
              is_state("binary_sensor.living_room_motion_occupancy", "on") or
              is_state("remote.living_room_apple_tv", "on") )
          }}
        delay_off: "00:10:00"

      bathroom_occupied:
        friendly_name: Bathroom Occupied
        icon_template: mdi:walk
        value_template: >
          {{ is_state("input_boolean.bathroom_occupancy_automation", "on") and (
              is_state("binary_sensor.bathroom_motion_sensor", "on") or
              is_state("binary_sensor.bathroom_shower", "on"))
          }}
        delay_off: "00:05:00"

      kitchen_occupied:
        friendly_name: Kitchen Occupied
        icon_template: mdi:walk
        value_template: >
          {{ is_state("input_boolean.kitchen_occupancy_automation", "on") and
            is_state("binary_sensor.kitchen_motion_sensor", "on") }}
        delay_off: "00:02:00"

      bathroom_shower:
        friendly_name: Bathroom Shower
        value_template: >
          {{ states("sensor.bathroom_humidity") | float(0) > 60 }}

      # is_state("bathroom_door_closed_inside", "on"))
      # bathroom_door_closed_inside:
      #   friendly_name: Bathroom Door Closed Inside
      #   value_template: >
      #     {{ (as_timestamp(states.binary_sensor.bathroom_motion.last_changed) > as_timestamp(states.binary_sensor.bathroom_door.last_changed) or
      #         as_timestamp(states.binary_sensor.bathroom_shower.last_changed) > as_timestamp(states.binary_sensor.bathroom_door.last_changed)) and
      #         is_state("binary_sensor.bathroom_door", "off") }}

      office_occupied:
        friendly_name: Office Occupied
        icon_template: mdi:walk
        value_template: >
          {{ is_state("input_boolean.office_occupancy_automation", "on") and
              (is_state("binary_sensor.office_motion_sensor", "on") or
                (is_state("binary_sensor.stk_jchadda_active", "on"
                  and is_state("device_tracker.stk_jchadda", "home"))
              ))
          }}
        delay_off: "00:10:00"

      leas_occupied:
        friendly_name: Leas Occupied
        icon_template: mdi:walk
        value_template: >
          {{ is_state("input_boolean.leas_occupancy_automation", "on") and
              is_state("binary_sensor.leas_motion_sensor", "on")
          }}
        delay_off: "00:10:00"

      claras_occupied:
        friendly_name: Claras Occupied
        icon_template: mdi:walk
        value_template: >
          {{ is_state("input_boolean.claras_occupancy_automation", "on") and
              is_state("binary_sensor.claras_motion_sensor", "on")
          }}
        delay_off: "00:10:00"

      entrance_occupied:
        friendly_name: Entrance Occupied
        icon_template: mdi:walk
        value_template: >
          {{ is_state("input_boolean.entrance_occupancy_automation", "on") and (
              is_state("binary_sensor.entrance_motion_sensor", "on") or
              is_state("binary_sensor.entrance_door", "on"))
          }}
        delay_off: "00:01:00"

      dining_room_occupied:
        friendly_name: Dining Room Occupied
        icon_template: mdi:walk
        value_template: >
          {{ is_state("input_boolean.dining_room_occupancy_automation", "on") and
              is_state("binary_sensor.dining_room_motion_sensor", "on")
          }}
        delay_off: "00:02:00"

      parents_hallway_occupied:
        friendly_name: Parents Hallway Occupied
        icon_template: mdi:walk
        value_template: >
          {{ is_state("input_boolean.parents_hallway_occupancy_automation", "on") and
              is_state("binary_sensor.parents_hallway_motion_sensor", "on")
          }}

      kids_hallway_occupied:
        friendly_name: Kids Hallway Occupied
        icon_template: mdi:walk
        value_template: >
          {{ is_state("input_boolean.kids_hallway_occupancy_automation", "on") and
              is_state("binary_sensor.kids_hallway_motion_sensor", "on")
          }}
