input_boolean:
  bedroom_occupancy_automation:
    name: Bedroom Motion Detection
    icon: mdi:eye-outline
  living_room_occupancy_automation:
    name: Living Room Motion Detection
    icon: mdi:eye-outline
  bathroom_occupancy_automation:
    name: Bathroom Motion Detection
    icon: mdi:eye-outline
  hallway_occupancy_automation:
    name: Hallway Motion Detection
    icon: mdi:eye-outline
  kitchen_occupancy_automation:
    name: Kitchen Motion Detection
    icon: mdi:eye-outline
  guest_bedroom_occupancy_automation:
    name: Guest Bedroom Motion Detection
    icon: mdi:eye-outline
  office_occupancy_automation:
    name: Office Motion Detection
    icon: mdi:eye-outline

group:
  Occupancy Automation:
    - input_boolean.bedroom_occupancy_automation
    - input_boolean.living_room_occupancy_automation
    - input_boolean.bathroom_occupancy_automation
    - input_boolean.hallway_occupancy_automation
    - input_boolean.kitchen_occupancy_automation
    - input_boolean.guest_bedroom_occupancy_automation
    - input_boolean.office_occupancy_automation

  Occupancy:
    - binary_sensor.bedroom_occupied
    - binary_sensor.living_room_occupied
    - binary_sensor.bathroom_occupied
    - binary_sensor.hallway_occupied
    - binary_sensor.kitchen_occupied
    - binary_sensor.guest_bedroom_occupied
    - binary_sensor.office_occupied

binary_sensor:
  - platform: template
    sensors:
      bedroom_occupied:
        friendly_name: Bedroom Occupied
        icon_template: mdi:walk
        value_template: >
          {{ is_state("input_boolean.bedroom_occupancy_automation", "on") and (
               is_state("binary_sensor.bedroom_motion_ias_zone", "on") or
               is_state("binary_sensor.working", "on")
             )
          }}
        delay_off: "00:10:00"

      living_room_occupied:
        friendly_name: Living Room Occupied
        icon_template: mdi:walk
        value_template: >
          {{ is_state("input_boolean.living_room_occupancy_automation", "on") and (
              is_state("binary_sensor.living_room_motion_sensor", "on") or
              is_state("remote.living_room", "on") )
          }}
        delay_off: "00:10:00"

      hallway_occupied:
        friendly_name: Hallway Occupied
        icon_template: mdi:walk
        value_template: >
          {{ is_state("input_boolean.hallway_occupancy_automation", "on") and
            is_state("binary_sensor.hallway_motion", "on") }}
        delay_off: "00:01:00"

      bathroom_occupied:
        friendly_name: Bathroom Occupied
        icon_template: mdi:walk
        value_template: >
          {{ is_state("input_boolean.bathroom_occupancy_automation", "on") and (
              is_state("binary_sensor.bathroom_motion", "on") or
              is_state("binary_sensor.bathroom_shower", "on") or
              is_state("bathroom_door_closed_inside", "on"))
          }}
        delay_off: "00:05:00"

      kitchen_occupied:
        friendly_name: Kitchen Occupied
        icon_template: mdi:walk
        value_template: >
          {{ is_state("input_boolean.kitchen_occupancy_automation", "on") and
            is_state("binary_sensor.kitchen_motion", "on") }}
        delay_off: "00:05:00"

      guest_bedroom_occupied:
        friendly_name: Guest Bedroom Occupied
        icon_template: mdi:walk
        value_template: >
          {{ is_state("input_boolean.guest_bedroom_occupancy_automation", "on") and
             is_state("binary_sensor.guest_bedroom_motion", "on") }}
        delay_off: "00:10:00"

      bathroom_shower:
        friendly_name: Bathroom Shower
        value_template: >
          {{ states("sensor.bathroom_humidity") | float(0) > 60 }}

      bathroom_door_closed_inside:
        friendly_name: Bathroom Door Closed Inside
        value_template: >
          {{ (as_timestamp(states.binary_sensor.bathroom_motion.last_changed) > as_timestamp(states.binary_sensor.bathroom_door.last_changed) or
              as_timestamp(states.binary_sensor.bathroom_shower.last_changed) > as_timestamp(states.binary_sensor.bathroom_door.last_changed)) and
              is_state("binary_sensor.bathroom_door", "off") }}

      office_occupied:
        friendly_name: Office Occupied
        icon_template: mdi:walk
        value_template: >
          {{ is_state("input_boolean.office_occupancy_automation", "on") and
              is_state("binary_sensor.office_motion_ias_zone", "on")
          }}
        delay_off: "00:10:00"

automation:
  - alias: Occupancy - Bedroom sleep on
    id: ffa9b5a5-db81-44a1-810b-cfde7bd745f0
    trigger:
      - platform: state
        entity_id: input_boolean.johnny_asleep
        to: 'on'
      - platform: state
        entity_id: input_boolean.kajsa_asleep
        to: 'on'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.bedroom_occupancy_automation

  - alias: Occupancy - Bedroom sleep off
    id: d075be9d-9682-41d1-b30f-01dbb75c2a47
    trigger:
      - platform: state
        entity_id: input_boolean.johnny_asleep
        to: 'off'
      - platform: state
        entity_id: input_boolean.kajsa_asleep
        to: 'off'
    condition:
      - condition: state
        entity_id: input_boolean.johnny_asleep
        state: 'off'
      - condition: state
        entity_id: input_boolean.kajsa_asleep
        state: 'off'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.bedroom_occupancy_automation

  - alias: Occupancy - Guest bedroom sleep on
    id: 87ade7db-c8df-40b3-adef-5e55050adf82
    trigger:
      - platform: state
        entity_id: input_boolean.guest_asleep
        to: 'on'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.guest_bedroom_occupancy_automation

  - alias: Occupancy - Guest bedroom sleep off
    id: 63131733-159f-4640-9c99-eb89a03dfb89
    trigger:
      - platform: state
        entity_id: input_boolean.guest_asleep
        to: 'off'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.guest_bedroom_occupancy_automation

  - alias: Occupancy - Enable occupancy automation when away
    id: 52671c90-3f85-4cd3-b834-31fc92b7a726
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm
        to: 'armed_away'
    action:
      - service: input_boolean.turn_on
        entity_id:
          - input_boolean.bedroom_occupancy_automation
          - input_boolean.living_room_occupancy_automation
          - input_boolean.hallway_occupancy_automation
          - input_boolean.bathroom_occupancy_automation
          - input_boolean.kitchen_occupancy_automation
          - input_boolean.guest_bedroom_occupancy_automation

  - alias: Occupancy - Enable occupancy automation when waking up
    id: 60cb22d8-43a7-48bc-b825-7acc1086c986
    trigger:
      - platform: state
        entity_id: input_boolean.everyone_asleep
        to: 'off'
    action:
      - service: input_boolean.turn_on
        entity_id:
          - input_boolean.living_room_occupancy_automation
          - input_boolean.hallway_occupancy_automation
          - input_boolean.bathroom_occupancy_automation
          - input_boolean.kitchen_occupancy_automation

  - alias: Occupancy - Disable automation when turning lights off
    id: 5f7169f5-9c13-46c6-9af4-e03ea4ecba02
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: bedroom_dimmer
          event: 4002
      - platform: event
        event_type: deconz_event
        event_data:
          id: living_room_dimmer
          event: 4002
      - platform: event
        event_type: deconz_event
        event_data:
          id: hallway_dimmer
          event: 4002
      - platform: event
        event_type: deconz_event
        event_data:
          id: bathroom_dimmer
          event: 4002
      - platform: event
        event_type: deconz_event
        event_data:
          id: kitchen_dimmer
          event: 4002
      - platform: event
        event_type: deconz_event
        event_data:
          id: guest_bedroom_dimmer
          event: 4002
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.{{ trigger.event.data.id.split('_')[0] }}_occupancy_automation

  - alias: Occupancy - Enable automation when turning lights on
    id: a6489c62-8b1f-474b-a644-d73aca0c2ab9
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: bedroom_dimmer
          event: 1002
      - platform: event
        event_type: deconz_event
        event_data:
          id: living_room_dimmer
          event: 1002
      - platform: event
        event_type: deconz_event
        event_data:
          id: hallway_dimmer
          event: 1002
      - platform: event
        event_type: deconz_event
        event_data:
          id: bathroom_dimmer
          event: 1002
      - platform: event
        event_type: deconz_event
        event_data:
          id: kitchen_dimmer
          event: 1002
      - platform: event
        event_type: deconz_event
        event_data:
          id: guest_bedroom_dimmer
          event: 1002
    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.{{ trigger.event.data.id.split('_')[0] }}_occupancy_automation
