input_boolean:
  bedroom_occupancy_automation:
    name: Bedroom Motion Detection
    icon: mdi:eye-outline
  living_room_occupancy_automation:
    name: Living Room Motion Detection
    icon: mdi:eye-outline
  bathroom_occupancy_automation:
    name: Bathroom Motion Detection
    icon: mdi:eye-outline
  hallway_occupancy_automation:
    name: Hallway Motion Detection
    icon: mdi:eye-outline
  kitchen_occupancy_automation:
    name: Kitchen Motion Detection
    icon: mdi:eye-outline
  office_occupancy_automation:
    name: Office Motion Detection
    icon: mdi:eye-outline
  leas_occupancy_automation:
    name: Leas Motion Detection
    icon: mdi:eye-outline
  claras_occupancy_automation:
    name: Claras Motion Detection
    icon: mdi:eye-outline
  entrance_occupancy_automation:
    name: Entrance Motion Detection
    icon: mdi:eye-outline
  dining_room_occupancy_automation:
    name: Dining Room Motion Detection
    icon: mdi:eye-outline
  parents_hallway_occupancy_automation:
    name: Parents Hallway Motion Detection
    icon: mdi:eye-outline

group:
  Occupancy Automation:
    - input_boolean.bedroom_occupancy_automation
    - input_boolean.living_room_occupancy_automation
    - input_boolean.bathroom_occupancy_automation
    - input_boolean.hallway_occupancy_automation
    - input_boolean.kitchen_occupancy_automation
    - input_boolean.office_occupancy_automation
    - input_boolean.leas_occupancy_automation
    - input_boolean.claras_occupancy_automation
    - input_boolean.entrance_occupancy_automation
    - input_boolean.dining_room_occupancy_automation
    - input_boolean.office_hallway_occupancy_automation

  Occupancy:
    - binary_sensor.bedroom_occupied
    - binary_sensor.living_room_occupied
    - binary_sensor.bathroom_occupied
    - binary_sensor.hallway_occupied
    - binary_sensor.kitchen_occupied
    - binary_sensor.office_occupied
    - binary_sensor.leas_occupied
    - binary_sensor.claras_occupied
    - binary_sensor.entrance_occupied
    - binary_sensor.dining_room_occupied
    - binary_sensor.office_hallway_occupied

binary_sensor:
  - platform: template
    sensors:
      bedroom_occupied:
        friendly_name: Bedroom Occupied
        icon_template: mdi:walk
        value_template: >
          {{ is_state("input_boolean.bedroom_occupancy_automation", "on") and (
               is_state("binary_sensor.bedroom_motion_sensor", "on") or
               is_state("binary_sensor.working", "on")
             )
          }}
        delay_off: "00:10:00"

      living_room_occupied:
        friendly_name: Living Room Occupied
        icon_template: mdi:walk
        value_template: >
          {{ is_state("input_boolean.living_room_occupancy_automation", "on") and (
              is_state("binary_sensor.living_room_motion_occupancy", "on") or
              is_state("remote.living_room_apple_tv", "on") )
          }}
        delay_off: "00:10:00"

      bathroom_occupied:
        friendly_name: Bathroom Occupied
        icon_template: mdi:walk
        value_template: >
          {{ is_state("input_boolean.bathroom_occupancy_automation", "on") and (
              is_state("binary_sensor.bathroom_motion_sensor", "on") or
              is_state("binary_sensor.bathroom_shower", "on"))
          }}
        delay_off: "00:05:00"

      kitchen_occupied:
        friendly_name: Kitchen Occupied
        icon_template: mdi:walk
        value_template: >
          {{ is_state("input_boolean.kitchen_occupancy_automation", "on") and
            is_state("binary_sensor.kitchen_motion_sensor", "on") }}
        delay_off: "00:02:00"

      bathroom_shower:
        friendly_name: Bathroom Shower
        value_template: >
          {{ states("sensor.bathroom_humidity") | float(0) > 60 }}

      # is_state("bathroom_door_closed_inside", "on"))
      # bathroom_door_closed_inside:
      #   friendly_name: Bathroom Door Closed Inside
      #   value_template: >
      #     {{ (as_timestamp(states.binary_sensor.bathroom_motion.last_changed) > as_timestamp(states.binary_sensor.bathroom_door.last_changed) or
      #         as_timestamp(states.binary_sensor.bathroom_shower.last_changed) > as_timestamp(states.binary_sensor.bathroom_door.last_changed)) and
      #         is_state("binary_sensor.bathroom_door", "off") }}

      office_occupied:
        friendly_name: Office Occupied
        icon_template: mdi:walk
        value_template: >
          {{ is_state("input_boolean.office_occupancy_automation", "on") and
              (is_state("binary_sensor.office_motion_sensor", "on") or
                (is_state("binary_sensor.stk_jchadda_active", "on"
                  and is_state("device_tracker.stk_jchadda", "home"))
              ))
          }}
        delay_off: "00:10:00"

      leas_occupied:
        friendly_name: Leas Occupied
        icon_template: mdi:walk
        value_template: >
          {{ is_state("input_boolean.leas_occupancy_automation", "on") and
              is_state("binary_sensor.leas_motion_sensor", "on")
          }}
        delay_off: "00:10:00"

      claras_occupied:
        friendly_name: Claras Occupied
        icon_template: mdi:walk
        value_template: >
          {{ is_state("input_boolean.claras_occupancy_automation", "on") and
              is_state("binary_sensor.claras_motion_sensor", "on")
          }}
        delay_off: "00:10:00"

      entrance_occupied:
        friendly_name: Entrance Occupied
        icon_template: mdi:walk
        value_template: >
          {{ is_state("input_boolean.entrance_occupancy_automation", "on") and (
              is_state("binary_sensor.entrance_motion_sensor", "on") or
              is_state("binary_sensor.entrance_door", "on"))
          }}
        delay_off: "00:01:00"

      dining_room_occupied:
        friendly_name: Dining Room Occupied
        icon_template: mdi:walk
        value_template: >
          {{ is_state("input_boolean.dining_room_occupancy_automation", "on") and
              is_state("binary_sensor.dining_room_motion_sensor", "on")
          }}
        delay_off: "00:02:00"

      parents_hallway_occupied:
        friendly_name: Parents Hallway Occupied
        icon_template: mdi:walk
        value_template: >
          {{ false }}
        # value_template: >
        #   {{ is_state("input_boolean.entrance_occupancy_automation", "on") and
        #       is_state("binary_sensor.entrance_motion_ias_zone", "on")
        #   }}
        delay_off: "00:01:00"

automation:
  - alias: Occupancy - Enable occupancy automation when away
    id: 52671c90-3f85-4cd3-b834-31fc92b7a726
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm
        to: 'armed_away'
    action:
      - service: input_boolean.turn_on
        entity_id:
          - input_boolean.bedroom_occupancy_automation
          - input_boolean.living_room_occupancy_automation
          - input_boolean.hallway_occupancy_automation
          - input_boolean.bathroom_occupancy_automation
          - input_boolean.kitchen_occupancy_automation
          - input_boolean.office_occupancy_automation
          - input_boolean.leas_occupancy_automation
          - input_boolean.claras_occupancy_automation
          - input_boolean.entrance_occupancy_automation

  - alias: Occupancy - Enable occupancy automation when waking up
    id: 60cb22d8-43a7-48bc-b825-7acc1086c986
    trigger:
      - platform: state
        entity_id: input_boolean.everyone_asleep
        to: 'off'
    action:
      - service: input_boolean.turn_on
        entity_id:
          - input_boolean.living_room_occupancy_automation
          - input_boolean.hallway_occupancy_automation
          - input_boolean.bathroom_occupancy_automation
          - input_boolean.kitchen_occupancy_automation
          - input_boolean.entrance_occupancy_automation
