automation:
  - alias: Warn when main entrance has been open a long time
    id: 092a289a-4a68-45e8-b45b-aabd10cee285
    trigger:
      - platform: state
        entity_id: binary_sensor.main_entrance
        to: 'on'
        for: '00:10:00'
    action:
      - service: notify.all_phones
        data:
          title: "Main entrance open"
          message: "The main entrance door has been open for 10 minutes"

  - alias: Record when the main entrance is opened
    id: 792ac673-c2c5-4419-8f06-81b1de567e56
    trigger:
      - platform: state
        entity_id: binary_sensor.main_entrance
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.perimeter_warning
        state: 'on'
    action:
      - service: aarlo.camera_start_recording
        data:
          entity_id:
            - camera.aarlo_hallway
            - camera.aarlo_living_room
          duration: 60

  - alias: Warn when leaving if windows are open
    id: 518f6cc7-fb96-4b5b-b472-98c0a2ccced5
    trigger:
      - platform: state
        entity_id: binary_sensor.main_entrance
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.perimeter_warning
        state: 'on'
      - condition: state
        entity_id: binary_sensor.hallway_motion
        state: 'on'
      - condition: or
        conditions:
        - condition: state
          entity_id: binary_sensor.balcony_entrance
          state: 'on'
        - condition: state
          entity_id: binary_sensor.bedroom_window
          state: 'on'
        - condition: state
          entity_id: binary_sensor.living_room_window_left
          state: 'on'
        - condition: state
          entity_id: binary_sensor.living_room_window_right
          state: 'on'
        - condition: state
          entity_id: binary_sensor.bathroom_window
          state: 'on'
        - condition: state
          entity_id: binary_sensor.kitchen_window_left
          state: 'on'
        - condition: state
          entity_id: binary_sensor.kitchen_window_right
          state: 'on'
        - condition: state
          entity_id: binary_sensor.guest_bedroom_window
          state: 'on'
    action:
      - service: notify.all_phones
        data:
          title: "Window open"
          message: "Someone is leaving and a window is open"

  - alias: Notify if windows are open when it starts to rain or snow
    id: 2bfe720e-529a-4acd-ac45-12f1ef35b78f
    trigger:
      - platform: state
        entity_id: weather.smhi_home
        to: 'rainy'
      - platform: state
        entity_id: weather.smhi_home
        to: 'snowy'
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: binary_sensor.bedroom_window
          state: 'on'
        - condition: state
          entity_id: binary_sensor.balcony_entrance
          state: 'on'
        - condition: state
          entity_id: binary_sensor.bathroom_window
          state: 'on'
        - condition: state
          entity_id: binary_sensor.kitchen_window_left
          state: 'on'
        - condition: state
          entity_id: binary_sensor.kitchen_window_right
          state: 'on'
        - condition: state
          entity_id: binary_sensor.guest_bedroom_window
          state: 'on'
    action:
      - service: notify.all_phones
        data:
          title: "Rain is coming"
          message: "It is starting to rain and there are windows open. Please close them."
