sensor:
- platform: hasl
  ri4key: !secret hasl_ri4key
  si2key: !secret hasl_si2key
  tl2key: !secret hasl_tl2key
  sensors:
   - friendly_name: Ulriksdal
     sensor_type: departures
     siteid: 9508
     direction: 1
     lines:
       - "40"
       - "41"
       - "41X"
       - "42"
       - "42X"
       - "45"
     traffic_class: train
   # - friendly_name: Trafikstatus
   #   sensor_type: status
