group:
input_boolean:
  sleep_automation:
    name: Sleep Automation
    icon: mdi:sleep

  everyone_asleep:
    name: Everyone asleep
    icon: mdi:sleep

  johnny_asleep:
    name: Johnny asleep
    icon: mdi:sleep

  kajsa_asleep:
    name: Kajsa asleep
    icon: mdi:sleep

  lea_asleep:
    name: Lea Asleep
    icon: mdi:sleep

  clara_asleep:
    name: Clara Asleep
    icon: mdi:sleep

  guest_asleep:
    name: Guest Asleep
    icon: mdi:sleep

automation:
  - alias: Toggle all asleep on
    id: ba22f811-2003-4435-be56-60ae59fb9611
    trigger:
      - platform: state
        entity_id: input_boolean.johnny_asleep
        to: 'on'
      - platform: state
        entity_id: input_boolean.kajsa_asleep
        to: 'on'
      - platform: state
        entity_id: input_boolean.lea_asleep
        to: 'on'
      - platform: state
        entity_id: input_boolean.clara_asleep
        to: 'on'
      - platform: state
        entity_id: input_boolean.guest_asleep
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.sleep_automation
        state: 'on'
      - condition: and
        conditions:
          - condition: or
            conditions:
            - condition: and
              conditions:
                - condition: state
                  entity_id: person.johnny
                  state: 'home'
                - condition: state
                  entity_id: input_boolean.johnny_asleep
                  state: 'on'
            - condition: state
              entity_id: person.johnny
              state: 'not_home'
          - condition: or
            conditions:
            - condition: and
              conditions:
                - condition: state
                  entity_id: person.kajsa
                  state: 'home'
                - condition: state
                  entity_id: input_boolean.kajsa_asleep
                  state: 'on'
            - condition: state
              entity_id: person.kajsa
              state: 'not_home'
          - condition: or
            conditions:
            - condition: and
              conditions:
                - condition: state
                  entity_id: input_boolean.guest_mode
                  state: 'on'
                - condition: or
                  conditions:
                    - condition: state
                      entity_id: input_boolean.guest_asleep
                      state: 'on'
            - condition: state
              entity_id: input_boolean.guest_mode
              state: 'off'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.everyone_asleep

  - alias: Toggle all asleep off
    id: b7fe69fa-411e-481f-bb18-5018a81e7818
    trigger:
      - platform: state
        entity_id: input_boolean.johnny_asleep
        to: 'off'
      - platform: state
        entity_id: input_boolean.kajsa_asleep
        to: 'off'
      - platform: state
        entity_id: input_boolean.lea_asleep
        to: 'off'
      - platform: state
        entity_id: input_boolean.clara_asleep
        to: 'off'
      - platform: state
        entity_id: input_boolean.guest_asleep
        to: 'off'
    condition:
      - condition: state
        entity_id: input_boolean.sleep_automation
        state: 'on'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.everyone_asleep
