group:
  Sleep Status:
    - input_boolean.everyone_asleep
    - input_boolean.johnny_asleep
    - input_boolean.kajsa_asleep
    - input_boolean.guest_asleep

input_boolean:
  sleep_automation:
    name: Sleep Automation
    icon: mdi:sleep

  everyone_asleep:
    name: Everyone asleep
    icon: mdi:sleep

  johnny_asleep:
    name: Johnny asleep
    icon: mdi:sleep

  kajsa_asleep:
    name: Kajsa asleep
    icon: mdi:sleep

  guest_asleep:
    name: Guest Asleep
    icon: mdi:sleep

automation:
  - alias: Toggle all asleep on
    trigger:
      - platform: state
        entity_id: input_boolean.johnny_asleep
        to: 'on'
      - platform: state
        entity_id: input_boolean.kajsa_asleep
        to: 'on'
      - platform: state
        entity_id: input_boolean.guest_asleep
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.sleep_automation
        state: 'on'
      - condition: and
        conditions:
          - condition: or
            conditions:
            - condition: and
              conditions:
                - condition: state
                  entity_id: device_tracker.johnnysiphone
                  state: 'home'
                - condition: state
                  entity_id: input_boolean.johnny_asleep
                  state: 'on'
            - condition: state
              entity_id: device_tracker.johnnysiphone
              state: 'not_home'
          - condition: or
            conditions:
            - condition: and
              conditions:
                - condition: state
                  entity_id: device_tracker.kajsasiphone
                  state: 'home'
                - condition: state
                  entity_id: input_boolean.kajsa_asleep
                  state: 'on'
            - condition: state
              entity_id: device_tracker.kajsasiphone
              state: 'not_home'
          - condition: or
            conditions:
            - condition: and
              conditions:
                - condition: state
                  entity_id: input_boolean.guest_mode
                  state: 'on'
                - condition: state
                  entity_id: input_boolean.guest_asleep
                  state: 'on'
            - condition: state
              entity_id: input_boolean.guest_mode
              state: 'off'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.everyone_asleep

  - alias: Toggle all asleep off
    trigger:
      - platform: state
        entity_id: input_boolean.johnny_asleep
        to: 'off'
      - platform: state
        entity_id: input_boolean.kajsa_asleep
        to: 'off'
      - platform: state
        entity_id: input_boolean.guest_asleep
        to: 'off'
    condition:
      - condition: state
        entity_id: input_boolean.sleep_automation
        state: 'on'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.everyone_asleep

## Button ##
  - alias: Toggle Johnny Asleep
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: johnny_asleep
          event: 1002
      - platform: event
        event_type: deconz_event
        event_data:
          id: johnny_asleep
          event: 1003
    condition:
      - condition: state
        entity_id: device_tracker.johnnysiphone
        state: 'home'
    action:
      - service: input_boolean.toggle
        entity_id: input_boolean.johnny_asleep

  - alias: Toggle Kajsa Asleep
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: kajsa_asleep
          event: 1002
      - platform: event
        event_type: deconz_event
        event_data:
          id: kajsa_asleep
          event: 1003
    condition:
      - condition: state
        entity_id: device_tracker.kajsasiphone
        state: 'home'
    action:
      - service: input_boolean.toggle
        entity_id: input_boolean.kajsa_asleep

  - alias: Toggle guest asleep on
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: guest_asleep
          event: 1002
      - platform: event
        event_type: deconz_event
        event_data:
          id: guest_asleep
          event: 1003
    action:
      - service: input_boolean.toggle
        entity_id: input_boolean.guest_asleep

  - alias: Finish timers when everyone asleep toggles
    trigger:
      - platform: state
        entity_id: input_boolean.everyone_asleep
    action:
      - service: timer.finish
        entity_id: timer.bedroom_lights
      - service: timer.finish
        entity_id: timer.bedroom_lights
      - service: timer.finish
        entity_id: timer.living_room_lights
      - service: timer.finish
        entity_id: timer.bathroom_lights
      - service: timer.finish
        entity_id: timer.hallway_lights
      - service: timer.finish
        entity_id: timer.kitchen_lights
      - service: timer.finish
        entity_id: timer.guest_bedroom_lights
