automation:
  - alias: Notify and turn on lights when smoke detected
    trigger:
      - platform: state
        entity_id: binary_sensor.bedroom_smoke
        to: 'on'
      - platform: state
        entity_id: binary_sensor.hallway_smoke
        to: 'on'
      - platform: state
        entity_id: binary_sensor.guest_bedroom_smoke
        to: 'on'
    action:
      - service: script.turn_on
        entity_id: script.scene_home_full
      - service: camera.aarlo_start_recording
        data:
          entity_id: camera.aarlo_hallway
          duration: 60
      - service: camera.aarlo_start_recording
        data:
          entity_id: camera.aarlo_living_room
          duration: 60
      - service: notify.all_phones
        data_template:
          title: "[{{ trigger.entity_id }}] Smoke detected"
          message: "Please contact anyone at home or fire department."
