switch:
  - platform: template
    switches:
      living_room_sonos_night_sound:
        friendly_name: "Night Sound"
        value_template: "{{ state_attr('media_player.living_room', 'night_sound') }}"
        icon_template: mdi:weather-night
        turn_on:
          service: sonos.set_option
          data:
            entity_id: media_player.living_room
            night_sound: true
        turn_off:
          service: sonos.set_option
          data:
            entity_id: media_player.living_room
            night_sound: false
      living_room_sonos_speech_enhance:
        friendly_name: "Speech Enhance"
        value_template: "{{ state_attr('media_player.living_room', 'speech_enhance') }}"
        icon_template: mdi:voice
        turn_on:
          service: sonos.set_option
          data:
            entity_id: media_player.living_room
            speech_enhance: true
        turn_off:
          service: sonos.set_option
          data:
            entity_id: media_player.living_room
            speech_enhance: false

input_boolean:
  music_automation:
    name: Music Automation
    icon: mdi:playlist-music-outline

automation:
  - alias: Turn on background music when baby asleep
    id: c6daf5b4-998a-46b7-b8b9-152c674c1ee7
    trigger:
      - platform: state
        entity_id: input_boolean.guest_asleep
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.music_automation
        state: 'on'
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
    action:
      - service: media_player.volume_set
        data:
          entity_id: media_player.kitchen
          volume_level: 0.07
      - service: media_player.select_source
        data:
          entity_id: media_player.kitchen
          source: 'Pure Pop Gold'

  - alias: Turn off background music when baby wakes up
    id: be1efed4-511e-46f5-96d9-828a57773a40
    trigger:
      - platform: state
        entity_id: input_boolean.guest_asleep
        to: 'off'
    condition:
      - condition: state
        entity_id: input_boolean.music_automation
        state: 'on'
    action:
      - service: media_player.volume_set
        data:
          entity_id: media_player.kitchen
          volume_level: 0.1
      - service: media_player.select_source
        data:
          entity_id: media_player.kitchen
          source: 'P4 Stockholm'

  - alias: Pause music automatically
    id: db29b1a6-c6bd-46d0-b99e-66635cf77386
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm
        to: 'armed_away'
      - platform: state
        entity_id: input_boolean.everyone_asleep
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.music_automation
        state: 'on'
    action:
      - service: sonos.set_sleep_timer
        data:
          entity_id: media_player.bedroom
          sleep_time: 0
      - service: sonos.set_sleep_timer
        data:
          entity_id: media_player.living_room
          sleep_time: 0
      - service: sonos.set_sleep_timer
        data:
          entity_id: media_player.bathroom
          sleep_time: 0
      - service: sonos.set_sleep_timer
        data:
          entity_id: media_player.kitchen
          sleep_time: 0

  - alias: Change radio station when there is sports on
    id: 50258570-5a46-4299-a9c8-a32c0fff14ca
    trigger:
      - platform: template
        value_template: "{{ 'sport' in state_attr('media_player.kitchen', 'media_artist')|lower }}"
    condition:
      - condition: state
        entity_id: input_boolean.music_automation
        state: 'on'
      - condition: state
        entity_id: media_player.kitchen
        state: playing
      - condition: template
        value_template: "{{ state_attr('media_player.kitchen', 'media_title') == 'P4 Stockholm' }}"
    action:
      - service: media_player.select_source
        data:
          entity_id: media_player.kitchen
          source: 'Pure Pop Gold'

  - alias: Disable night mode when going to bed
    id: c18548d5-8673-48e0-b10c-c24445289ec2
    trigger:
      - platform: state
        entity_id: input_boolean.everyone_asleep
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.music_automation
        state: 'on'
    action:
      - service: switch.turn_off
        entity_id:
          - switch.living_room_sonos_night_sound
          - switch.living_room_sonos_speech_enhance

  - alias: Sonos - Music on when bathroom occupied
    id: 739f8302-e70b-41dc-80b3-fe58d0263abe
    trigger:
      - platform: state
        entity_id: binary_sensor.bathroom_occupied
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.music_automation
        state: 'on'
      - condition: state
        entity_id: input_boolean.everyone_asleep
        state: 'off'
    action:
      - service: media_player.volume_set
        data:
          entity_id: media_player.bathroom
          volume_level: 0.08
      - service: media_player.select_source
        data:
          entity_id: media_player.bathroom
          source: 'Classic Singer/Songwriter'

  - alias: Sonos - Music off when bathroom unoccupied
    id: 990151c5-4deb-4a69-a654-28daa3b040c1
    trigger:
      - platform: state
        entity_id: binary_sensor.bathroom_occupied
        to: 'off'
    condition:
      - condition: state
        entity_id: input_boolean.music_automation
        state: 'on'
    action:
      - service: sonos.unjoin
        data:
          entity_id: media_player.bathroom
      - service: sonos.set_sleep_timer
        data:
          entity_id: media_player.bathroom
          sleep_time: 0
