automation:
  - alias: '[Themes] Automatically switch'
    id: 8a3f510a-a0de-47c6-984d-9b66e1094690
    trigger:
      - platform: homeassistant
        event: start
      - platform: state
        entity_id: sun.sun
        to: 'below_horizon'
      - platform: state
        entity_id: sun.sun
        to: 'above_horizon'
    action:
      - service: frontend.set_theme
        data_template:
          name: >-
            {% if is_state('sun.sun', 'below_horizon') %}
            ios-dark-mode-blue-red
            {% else %}
            ios-light-mode-light-green
            {% endif %}
