input_boolean:
  vacuum_automation:
    name: Vacuum Automation
    icon: mdi:robot-vacuum

  vacuum_return_on_disarm:
    name: Vacuum Return on Disarm
    icon: mdi:robot-vacuum

input_number:
  vacuum_time_remaining:
    name: Vacuum Time Remaining
    icon: mdi:history
    mode: box
    unit_of_measurement: min
    min: -1000
    max: 1000

input_select:
  vacuum_clean:
    name: Clean Zone
    icon: mdi:map-marker-radius
    initial: Choose
    options:
      - Choose
      - Bedroom
      - Living Room
      - Litterbox
      - Hallway
      - Kitchen
      - Guest Bedroom

  vacuum_go:
    name: Go to
    icon: mdi:map-marker-down
    initial: Choose
    options:
      - Choose
      - Home
      - Trash
      - Appear

automation:
  - alias: Kitchen send vacuum to trash
    id: 4c460640-8d90-44a4-b134-0b93e3c93a06
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: empty_vacuum
          event: 1002
    action:
      - service: script.turn_on
        entity_id: script.vacuum_go_trash
      - service: input_number.set_value
        data:
          entity_id: input_number.vacuum_time_remaining
          value: 120

  - alias: Kitchen send vacuum home
    id: cb778c1f-50ae-4587-8815-885393fbcb5f
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: empty_vacuum
          event: 1003
    action:
      - service: script.turn_on
        entity_id: script.vacuum_go_home

  - alias: Turn on vacuum when alarm is armed
    id: 9c00a656-8992-48dc-8bd3-351552bac64e
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm
        to: 'armed_away'
        for: '00:01:00'
      - platform: state
        entity_id: alarm_control_panel.alarm
        to: 'armed_away'
        for: '01:00:00'
      - platform: state
        entity_id: alarm_control_panel.alarm
        to: 'armed_away'
        for: '02:00:00'
      - platform: state
        entity_id: alarm_control_panel.alarm
        to: 'armed_away'
        for: '04:00:00'
    condition:
      - condition: state
        entity_id: input_boolean.vacuum_automation
        state: 'on'
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: 'off'
      - condition: template
        value_template: '{{ (as_timestamp(now()) - as_timestamp(states.automation.turn_on_vacuum_when_alarm_is_armed.attributes.last_triggered | default(0)) | int > 36000)}}'
      - condition: time
        after: '08:00:00'
        before: '20:00:00'
      - condition: numeric_state
        entity_id: input_number.vacuum_time_remaining
        above: -60
    action:
      - service: vacuum.start
        data:
          entity_id: vacuum.greta

  - alias: Turn off vacuum when alarm is disarmed
    id: 008dc98e-0bb8-492b-9e3a-f439be1f3398
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm
        to: 'disarmed'
    condition:
      - condition: state
        entity_id: vacuum.greta
        state: 'cleaning'
      - condition: state
        entity_id: input_boolean.vacuum_automation
        state: 'on'
      - condition: state
        entity_id: input_boolean.vacuum_return_on_disarm
        state: 'on'
    action:
      - service: vacuum.return_to_base
        data:
          entity_id: vacuum.greta

  - alias: Notify when there is a vacuum issue
    id: ee19ed8b-8c7a-4a10-ab4e-c2bf6a86e40c
    trigger:
      - platform: state
        entity_id: vacuum.greta
        to: 'error'
    action:
      - service: notify.all_phones
        data:
          title: "Greta is stuck"
          message: "Greta has reported an error. Make sure that she is not stuck."

  - alias: Notify when the vacuum needs emptying
    id: b2cd92cb-a73f-4646-b173-c61f54041cd7
    trigger:
      - platform: numeric_state
        entity_id: input_number.vacuum_time_remaining
        below: 0
    action:
      - service: notify.all_phones
        data:
          title: "Greta needs emptying"
          message: "Press the vacuum button by the kitchen bin to send Greta there."

  - alias: Vacuum - Update time remaining
    id: 47f91809-4154-4d6f-80a8-acdda1c304e7
    trigger:
      - platform: state
        entity_id: vacuum.greta
        to: 'docked'
    action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.vacuum_time_remaining
          value: "{{ states('input_number.vacuum_time_remaining')|int - state_attr('vacuum.greta', 'cleaning_time')|int }}"

  - alias: Activate chosen cleanup
    id: 5f67fa62-011b-4d26-943d-9f9b135043ac
    trigger:
      - platform: state
        entity_id: input_select.vacuum_clean
    action:
      - service: script.turn_on
        data_template:
          entity_id: script.vacuum_clean_{{ states('input_select.vacuum_clean')|lower|replace(" ", "_") }}
      - service: input_select.select_option
        data_template:
          entity_id: input_select.vacuum_clean
          option: Choose

  - alias: Activate chosen go target
    id: 2b3ecc49-1b3e-4277-a238-6945c2d8e126
    trigger:
      - platform: state
        entity_id: input_select.vacuum_go
    action:
      - service: script.turn_on
        data_template:
          entity_id: script.vacuum_go_{{ states('input_select.vacuum_go')|lower|replace(" ", "_") }}
      - service: input_select.select_option
        data_template:
          entity_id: input_select.vacuum_go
          option: Choose
