automation:
  - alias: Notify and turn on lights when water detected in kitchen
    id: 10331dc8-b2c3-4cc1-afbb-d86249b6d1fa
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_water
        to: 'on'
    action:
      - service: script.turn_on
        entity_id: script.scene_kitchen_full
      - service: aarlo.camera_start_recording
        data:
          entity_id:
            - camera.aarlo_hallway
            - camera.aarlo_living_room
          duration: 60
      - service: notify.all_phones
        data:
          title: "** Water detected **"
          message: "Water detected in the kitchen!"

  - alias: Notify and turn on lights when water detected in bathroom
    id: d24359f4-698b-4ad2-aca7-c320303a92e4
    trigger:
      - platform: state
        entity_id: binary_sensor.bathroom_water
        to: 'on'
    action:
      - service: script.turn_on
        entity_id: script.scene_bathroom_full
      - service: aarlo.camera_start_recording
        data:
          entity_id:
            - camera.aarlo_hallway
            - camera.aarlo_living_room
          duration: 60
      - service: notify.all_phones
        data:
          title: "** Water detected **"
          message: "Water detected in the bathroom!"
