- alias: Check if ok if no movement but home
  trigger:
    - platform: state
      entity_id: group.indoor_motion
      to: 'off'
      for: '04:00:00'
  condition:
    - condition: state
      entity_id: group.household
      state: 'home'
      for: '04:00:00'
    - condition: state
      entity_id: input_boolean.kajsa_asleep
      state: 'off'
      for: '04:00:00'
    - condition: state
      entity_id: input_boolean.johnny_asleep
      state: 'off'
      for: '04:00:00'
  action:
    - service: notify.all_phones
      data:
        title: "Someone home but no movement"
        message: "No movement detected for 4 hours! Call and make sure that they are ok."
