- alias: Home lights on
  trigger:
    - platform: numeric_state
      entity_id: sensor.living_room_luminance
      below: 40
      for: '00:10:00'
    - platform: state
      entity_id: input_boolean.everyone_asleep
      to: 'off'
    - platform: state
      entity_id:
        - binary_sensor.living_room_motion_sensor
        - binary_sensor.hallway_motion
        - binary_sensor.kitchen_motion
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.light_automation
      state: 'on'
    - condition: or
      conditions:
        - condition: state
          entity_id: alarm_control_panel.alarm
          state: 'disarmed'
        - condition: state
          entity_id: alarm_control_panel.alarm
          state: 'armed_night'
    - condition: state
      entity_id: input_boolean.everyone_asleep
      state: 'off'
    - condition: numeric_state
      entity_id: sensor.living_room_luminance
      below: 40
    - condition: state
      entity_id: input_boolean.lights_needed
      state: 'off'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.lights_needed

- alias: Home lights off
  trigger:
    - platform: state
      entity_id: alarm_control_panel.alarm
      to: 'armed_away'
    - platform: numeric_state
      entity_id: sensor.living_room_luminance
      above: 40
      for: '00:10:00'
  condition:
    - condition: state
      entity_id: input_boolean.light_automation
      state: 'on'
    - condition: state
      entity_id: input_boolean.lights_needed
      state: 'on'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.lights_needed

- alias: Home lights on when alarm triggered
  trigger:
    - platform: state
      entity_id: alarm_control_panel.alarm
      to: 'triggered'
  action:
    - service: script.turn_on
      entity_id: script.scene_lights_full

- alias: Home lights off after alarm triggered
  trigger:
    - platform: state
      entity_id: alarm_control_panel.alarm
      from: 'triggered'
  action:
    - service: script.turn_on
      entity_id: script.scene_lights_off

- alias: Lights off when last person goes to bed
  trigger:
    - platform: state
      entity_id: input_boolean.everyone_asleep
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.lights_needed
      state: 'on'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.lights_needed

- alias: Lights off when not home
  trigger:
    - platform: time
      at: '22:30:00'
  condition:
    - condition: state
      entity_id: input_boolean.light_automation
      state: 'on'
    - condition: state
      entity_id: alarm_control_panel.alarm
      state: 'armed_away'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.lights_needed

- alias: Lights on when not home
  trigger:
    - platform: sun
      event: sunset
  condition:
    - condition: state
      entity_id: input_boolean.light_automation
      state: 'on'
    - condition: state
      entity_id: alarm_control_panel.alarm
      state: 'armed_away'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.lights_needed
