- alias: Notify and turn on lights when smoke detected
  trigger:
    - platform: state
      entity_id: binary_sensor.bedroom_smoke
      to: 'on'
    - platform: state
      entity_id: binary_sensor.hallway_smoke
      to: 'on'
    - platform: state
      entity_id: binary_sensor.guest_bedroom_smoke
      to: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.lights_full
    - service: ifttt.trigger
      data: {"event":"record_hallway"}
    - service: ifttt.trigger
      data: {"event":"record_living_room"}
    - service: notify.all_phones
      data_template:
        title: "[{{ trigger.entity_id }}] Smoke detected"
        message: "Please contact anyone at home or fire department."
