- alias: Notify and turn on lights when smoke detected
  trigger:
    - platform: state
      entity_id: binary_sensor.hallway_smoke
      to: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.lights_full
    - service: notify.all_phones
      data:
        title: "Smoke detected at home!"
        message: "Please contact anyone at home or fire department."
