- alias: Notify and turn on lights when water detected in kitchen
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_water
      to: 'on'
  action:
    - service: script.turn_on
      entity_id: script.scene_kitchen_full
    - service: ifttt.trigger
      data: {"event":"record_hallway"}
    - service: ifttt.trigger
      data: {"event":"record_living_room"}
    - service: notify.all_phones
      data:
        title: "** Water detected **"
        message: "Water detected in the kitchen!"

- alias: Notify and turn on lights when water detected in bathroom
  trigger:
    - platform: state
      entity_id: binary_sensor.bathroom_water
      to: 'on'
  action:
    - service: script.turn_on
      entity_id: script.scene_bathroom_full
    - service: ifttt.trigger
      data: {"event":"record_hallway"}
    - service: ifttt.trigger
      data: {"event":"record_living_room"}
    - service: notify.all_phones
      data:
        title: "** Water detected **"
        message: "Water detected in the bathroom!"
