- alias: Reset living room arlo motion boolean when triggered
  trigger:
    - platform: state
      entity_id: input_boolean.living_room_arlo_motion
      to: 'on'
      for: '00:00:01'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.living_room_arlo_motion

- alias: Reset hallway arlo motion boolean when triggered
  trigger:
    - platform: state
      entity_id: input_boolean.hallway_arlo_motion
      to: 'on'
      for: '00:00:01'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.hallway_arlo_motion
