- alias: Set Harmony activity using input_select
  trigger:
    platform: state
    entity_id: input_select.harmony
  action:
    service: remote.turn_on
    entity_id: remote.living_room
    data_template:
      activity: >
        {% if is_state("input_select.harmony", "TV") %}
          42817532
        {% elif is_state("input_select.harmony", "Apple TV") %}
          42807286
        {% elif is_state("input_select.harmony", "Music") %}
          29561682
        {% else %}
          -1
        {% endif %}

- alias: Update Harmony input_select
  trigger:
    platform: state
    entity_id: remote.living_room
  action:
    service: input_select.select_option
    data_template:
      entity_id: input_select.harmony
      option: "{{ state_attr('remote.living_room', 'current_activity') }}"

- alias: PowerOff Harmony when alarm is armed_away
  trigger:
    - platform: state
      entity_id: alarm_control_panel.alarm
      to: 'armed_away'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.harmony
        option: 'PowerOff'
