- alias: Activate chosen scene
  trigger:
    - platform: state
      entity_id: input_select.scene
  action:
    - service: script.turn_on
      data_template:
        entity_id: script.scene_{{ states('input_select.scene')|lower|replace(" ", "_") }}
    - service: input_select.select_option
      data_template:
        entity_id: input_select.scene
        option: Choose
