- alias: Guest Bedroom lights on
  trigger:
    - platform: state
      entity_id: input_boolean.lights_needed
      to: 'on'
    - platform: state
      entity_id: binary_sensor.guest_bedroom_motion
      to: 'off'
      for: '00:10:00'
  condition:
    - condition: state
      entity_id: input_boolean.lights_needed
      state: 'on'
    - condition: state
      entity_id: input_boolean.guest_bedroom_motion_detection_enabled
      state: 'on'
    - condition: state
      entity_id: input_boolean.guest_asleep
      state: 'off'
    - condition: state
      entity_id: binary_sensor.guest_bedroom_motion
      state: 'off'
      for: '00:10:00'
  action:
    - service: scene.turn_on
      entity_id: scene.guest_bedroom_dim

- alias: Guest Bedroom lights off
  trigger:
    - platform: state
      entity_id: input_boolean.lights_needed
      to: 'off'
    - platform: state
      entity_id: input_boolean.guest_asleep
      to: 'on'
  condition:
    - condition: state
      entity_id: binary_sensor.guest_bedroom_motion
      state: 'off'
      for: '00:10:00'
  action:
    - service: scene.turn_on
      entity_id: scene.guest_bedroom_off

- alias: Guest Bedroom lights normal when occupied
  trigger:
    - platform: state
      entity_id: binary_sensor.guest_bedroom_motion
      to: 'on'
    - platform: state
      entity_id: input_boolean.guest_asleep
      to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.lights_needed
      state: 'on'
    - condition: state
      entity_id: input_boolean.guest_bedroom_motion_detection_enabled
      state: 'on'
    - condition: state
      entity_id: input_boolean.guest_asleep
      state: 'off'
    - condition: state
      entity_id: light.guest_bedroom_ceiling_lamp
      state: 'off'
  action:
    - service: scene.turn_on
      data_template:
        entity_id: >-
          {% if is_state('input_boolean.lights_full', 'on') %}
          scene.guest_bedroom_full
          {% elif is_state('input_boolean.lights_needed', 'on') %}
          scene.guest_bedroom_normal
          {% endif %}
