- alias: Disable guest bedroom motion on button click
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: guest_bedroom_dimmer
        event: 4003
  condition:
    - condition: state
      entity_id: input_boolean.guest_bedroom_occupancy_automation
      state: 'on'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.guest_bedroom_occupancy_automation

- alias: Enable guest bedroom motion
  trigger:
    - platform: state
      entity_id: binary_sensor.guest_bedroom_motion
      to: 'off'
      for: '01:00:00'
    - platform: event
      event_type: deconz_event
      event_data:
        id: guest_bedroom_dimmer
        event: 1003
  condition:
    - condition: state
      entity_id: input_boolean.guest_bedroom_occupancy_automation
      state: 'off'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.guest_bedroom_occupancy_automation
    - service: script.turn_on
      data_template:
        entity_id: script.scene_guest_bedroom_{{ states('sensor.light_mode') }}
