- alias: Disable guest bedroom motion on button click
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: guest_bedroom_dimmer
        event: 4003
  condition:
    - condition: state
      entity_id: input_boolean.guest_bedroom_motion_detection_enabled
      state: 'on'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.guest_bedroom_motion_detection_enabled

- alias: Enable guest bedroom motion
  trigger:
    - platform: state
      entity_id: binary_sensor.guest_bedroom_motion
      to: 'off'
      for: '01:00:00'
    - platform: event
      event_type: deconz_event
      event_data:
        id: guest_bedroom_dimmer
        event: 1003
  condition:
    - condition: state
      entity_id: input_boolean.guest_bedroom_motion_detection_enabled
      state: 'off'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.guest_bedroom_motion_detection_enabled
    - service: script.turn_on
      data_template:
        entity_id: >-
          {% if is_state('input_boolean.light_automation', 'on') %}
          script.scene_guest_bedroom_dim
          {% else %}
          script.scene_guest_bedroom_off
          {% endif %}
